import type { Locale } from '../i18n';
import { cyrillicToLatin } from '../i18n/transliterate';

/**
 * District / interdistrict court within a region. After the user picks
 * one, its `name` is stored in `state.values.district_court_name` and
 * rendered into the document header.
 *
 * Data is the authoritative MySud court registry (mysud.uz official
 * mobile app). Each court has a short legal name + physical address;
 * both are shown in the picker button (name bolder line, address on
 * the second line) so users can pick the correct local court without
 * a separate lookup. Only `name` is written into the document.
 */
export interface DistrictCourtDef {
  code: string;
  regionCode: string;
  courtTypeCode: string;
  /** Short legal name used both for the button label AND written into
   *  the document as `district_court_name`. Templates may prepend
   *  type-prefixes like "Жиноят ишлари бўйича …" or "Фуқаролик ишлари
   *  бўйича …", so names here are kept SHORT (e.g. "Косонсой туман
   *  суди", not "Жиноят ишлари бўйича Косонсой туман суди"). */
  name: Record<Locale, string>;
  /** Physical address. Shown as the second line of the picker button
   *  (greyed-out style is impossible in Telegram inline buttons, but
   *  the second line still helps users disambiguate similarly-named
   *  courts). NOT written into the document. */
  address?: Record<Locale, string>;
}

function L(cy: string, la: string, ru: string): Record<Locale, string> {
  return { uz_cyrillic: cy, uz_latin: la, ru };
}

function D(
  code: string,
  regionCode: string,
  cy: string,
  la: string,
  ru: string,
  addr?: string,
): DistrictCourtDef {
  return {
    code,
    regionCode,
    courtTypeCode: 'fuqarolik',
    name: L(cy, la, ru),
    ...(addr ? { address: { uz_cyrillic: addr, uz_latin: addr, ru: addr } } : {}),
  };
}

/**
 * Compact constructor for non-fuqarolik courts where we have authoritative
 * MySud data. Caller provides:
 *   - cy: Cyrillic Uzbek SHORT name (without "Жиноят/Фуқаролик ишлари
 *     бўйича" prefix — templates add that themselves)
 *   - addr: physical address as shown in MySud (Latin form acceptable for
 *     all locales since addresses are location hints, not legal text)
 *
 * The Latin name is derived via cyrillicToLatin(); the Russian name keeps
 * the Cyrillic form (Russian-speaking Uzbeks read Cyrillic Uzbek place
 * names without issue).
 */
function makeRealCourt(
  type: 'jinoyat' | 'mamuriy' | 'iqtisodiy' | 'fuqarolik',
  code: string,
  regionCode: string,
  cy: string,
  addr: string,
): DistrictCourtDef {
  return {
    code,
    regionCode,
    courtTypeCode: type,
    name: { uz_cyrillic: cy, uz_latin: cyrillicToLatin(cy), ru: cy },
    address: { uz_cyrillic: addr, uz_latin: addr, ru: addr },
  };
}

const M = (code: string, region: string, cy: string, addr: string) =>
  makeRealCourt('mamuriy', code, region, cy, addr);
const I = (code: string, region: string, cy: string, addr: string) =>
  makeRealCourt('iqtisodiy', code, region, cy, addr);
const J = (code: string, region: string, cy: string, addr: string) =>
  makeRealCourt('jinoyat', code, region, cy, addr);
const Fr = (code: string, region: string, cy: string, addr: string) =>
  makeRealCourt('fuqarolik', code, region, cy, addr);

/**
 * Mirror a fuqarolik (civil) court entry to one of the other court
 * types. Cuts down on hand-written duplication — the civil-court list
 * is the source of truth for region/district coverage, and the other
 * three court types are derived from it by swapping the type word in
 * the displayed name.
 *
 * Why per-type substitutions are different:
 *   - jinoyat (criminal): document templates already prepend
 *     "Жиноят ишлари бўйича ..." themselves, so the name must NOT
 *     repeat the word — we strip " фуқаролик" entirely.
 *   - mamuriy (administrative) / iqtisodiy (economic): templates use
 *     the name as-is with just a postposition ("…раисига" / "…га"),
 *     so we swap "фуқаролик" with the appropriate type word.
 *
 * The code prefix changes ("fuq-" → "jin-" / "mam-" / "iqt-") so each
 * court type gets a unique key suitable for callback data.
 */
function mirrorFuqarolikFor(
  base: DistrictCourtDef,
  type: 'jinoyat' | 'mamuriy' | 'iqtisodiy',
): DistrictCourtDef {
  const codePrefix =
    type === 'jinoyat' ? 'jin' : type === 'mamuriy' ? 'mam' : 'iqt';

  const subs: Record<'cy' | 'la' | 'ru', [RegExp, string]> =
    type === 'jinoyat'
      ? {
          cy: [/ фуқаролик/g, ''],
          la: [/ fuqarolik/g, ''],
          ru: [/ гражданский/g, ''],
        }
      : type === 'mamuriy'
        ? {
            cy: [/фуқаролик/g, 'маъмурий'],
            la: [/fuqarolik/g, 'ma’muriy'],
            ru: [/гражданский/g, 'административный'],
          }
        : {
            cy: [/фуқаролик/g, 'иқтисодий'],
            la: [/fuqarolik/g, 'iqtisodiy'],
            ru: [/гражданский/g, 'экономический'],
          };

  return {
    code: base.code.replace(/^fuq-/, `${codePrefix}-`),
    regionCode: base.regionCode,
    courtTypeCode: type,
    name: {
      uz_cyrillic: base.name.uz_cyrillic.replace(subs.cy[0], subs.cy[1]),
      uz_latin: base.name.uz_latin.replace(subs.la[0], subs.la[1]),
      ru: base.name.ru.replace(subs.ru[0], subs.ru[1]),
    },
  };
}

/**
 * The civil-court list — hand-written, the source of truth for what
 * regions/districts exist. The arrays for jinoyat, mamuriy and
 * iqtisodiy are mechanically derived from this via mirrorFuqarolikFor.
 */
const FUQAROLIK_COURTS: DistrictCourtDef[] = [
  // ===== Андижон вилояти =====
  D('fuq-andijan-vsudi', 'andijan',
    'Андижон вилоят суди',
    'Andijon viloyat sudi',
    'Андижанский областной суд',
    'Andijon shahar, Alisher Navoiy shoh koʻchasi, 15-uy'),
  D('fuq-andijan-tlf', 'andijan',
    'Андижон туманлараро фуқаролик суди',
    'Andijon tumanlararo fuqarolik sudi',
    'Андижанский межрайонный гражданский суд',
    'Andijon shahri, Toshkent koʻchasi, 4-uy'),
  D('fuq-asaka-tlf', 'andijan',
    'Асака туманлараро фуқаролик суди',
    'Asaka tumanlararo fuqarolik sudi',
    'Асакинский межрайонный гражданский суд',
    'Asaka tumani, Ergashobod MFY, Ergashobod koʻchasi, 37-uy'),
  D('fuq-boston-tlf', 'andijan',
    'Бўстон туманлараро фуқаролик суди',
    'Boʻston tumanlararo fuqarolik sudi',
    'Бустанский межрайонный гражданский суд',
    'Boʻston tumani, Pillakor MFY, Mustaqillik koʻchasi, 32-uy'),
  D('fuq-izboskan-tlf', 'andijan',
    'Избоскан туманлараро фуқаролик суди',
    'Izboskan tumanlararo fuqarolik sudi',
    'Избосканский межрайонный гражданский суд',
    'Izboskan tumani, Poytugʻ shahri, Mirzo Ulugʻbek koʻchasi, 2-uy'),
  D('fuq-qorgontepa-tlf', 'andijan',
    'Қўрғонтепа туманлараро фуқаролик суди',
    'Qoʻrgʻontepa tumanlararo fuqarolik sudi',
    'Кургантепинский межрайонный гражданский суд',
    'Qoʻrgʻontepa shahri, Mustaqillik koʻchasi, 50A-uy'),
  D('fuq-xojaobod-tlf', 'andijan',
    'Хўжаобод туманлараро фуқаролик суди',
    'Xoʻjaobod tumanlararo fuqarolik sudi',
    'Ходжаабадский межрайонный гражданский суд',
    'Xoʻjaobod tumani, Anxor koʻchasi, 2-uy'),

  // ===== Бухоро вилояти =====
  D('fuq-bukhara-vsudi', 'bukhara',
    'Бухоро вилоят суди',
    'Buxoro viloyat sudi',
    'Бухарский областной суд',
    'Buxoro shahri, Yangihayot koʻchasi, 122-uy'),
  D('fuq-bukhara-tlf', 'bukhara',
    'Бухоро туманлараро фуқаролик суди',
    'Buxoro tumanlararo fuqarolik sudi',
    'Бухарский межрайонный гражданский суд',
    'Buxoro shahri, Gʻijduvon koʻchasi, 12-uy'),
  D('fuq-gijduvon-tlf', 'bukhara',
    'Ғиждувон туманлараро фуқаролик суди',
    'Gʻijduvon tumanlararo fuqarolik sudi',
    'Гиждуванский межрайонный гражданский суд',
    'Gʻijduvon tumani, Yu.Hamadoniy koʻchasi, 54-uy'),
  D('fuq-kogon-tlf', 'bukhara',
    'Когон туманлараро фуқаролик суди',
    'Kogon tumanlararo fuqarolik sudi',
    'Каганский межрайонный гражданский суд',
    'Kogon shahri, Qorovulbozor shoh koʻchasi, 2-uy'),
  D('fuq-qorakul-tlf', 'bukhara',
    'Қоракўл туманлараро фуқаролик суди',
    'Qoraqoʻl tumanlararo fuqarolik sudi',
    'Каракульский межрайонный гражданский суд',
    'Qoraqoʻl tumani, Doʻstlik MFY, Buxoro koʻchasi, 152-uy'),
  D('fuq-peshku-tlf', 'bukhara',
    'Пешку туманлараро фуқаролик суди',
    'Peshku tumanlararo fuqarolik sudi',
    'Пешкунский межрайонный гражданский суд',
    'Peshku tumani, Amir Temur koʻchasi, 5-uy'),
  D('fuq-romitan-tlf', 'bukhara',
    'Ромитан туманлараро фуқаролик суди',
    'Romitan tumanlararo fuqarolik sudi',
    'Ромитанский межрайонный гражданский суд',
    'Romitan tumani, A.Temur koʻchasi, 40-uy'),

  // ===== Жиззах вилояти =====
  D('fuq-jizzakh-vsudi', 'jizzakh',
    'Жиззах вилоят суди',
    'Jizzax viloyat sudi',
    'Джизакский областной суд',
    'Jizzax shahri, O.Azimov koʻchasi, 15-uy'),
  D('fuq-gallaorol-tlf', 'jizzakh',
    'Ғаллаорол туманлараро фуқаролик суди',
    'Gʻallaorol tumanlararo fuqarolik sudi',
    'Галляаральский межрайонный гражданский суд',
    'Gʻallaorol tumani, Sarbozor MFY, Shodlik koʻchasi, 17-uy'),
  D('fuq-dustlik-tlf', 'jizzakh',
    'Дўстлик туманлараро фуқаролик суди',
    'Doʻstlik tumanlararo fuqarolik sudi',
    'Дустликский межрайонный гражданский суд',
    'Doʻstlik tumani, Doʻstlik shahar, A.Navoiy MFY'),
  D('fuq-jizzakh-tlf', 'jizzakh',
    'Жиззах туманлараро фуқаролик суди',
    'Jizzax tumanlararo fuqarolik sudi',
    'Джизакский межрайонный гражданский суд',
    'Jizzax shahri, Xalqlar doʻstligi shoh koʻchasi'),
  D('fuq-zomin-tlf', 'jizzakh',
    'Зомин туманлараро фуқаролик суди',
    'Zomin tumanlararo fuqarolik sudi',
    'Зааминский межрайонный гражданский суд',
    'Zomin tumani'),
  D('fuq-forish-tf', 'jizzakh',
    'Фориш туман фуқаролик суди',
    'Forish tuman fuqarolik sudi',
    'Фаришский районный гражданский суд',
    'Forish tumani, Oqtepa QFY, Tutak qishlogʻi'),

  // ===== Қашқадарё вилояти =====
  D('fuq-qash-vsudi', 'kashkadarya',
    'Қашқадарё вилоят суди',
    'Qashqadaryo viloyat sudi',
    'Кашкадарьинский областной суд',
    'Qarshi shahri, Abdulla Oripov koʻchasi, 10A-uy'),
  D('fuq-guzor-tlf', 'kashkadarya',
    'Ғузор туманлараро фуқаролик суди',
    'Gʻuzor tumanlararo fuqarolik sudi',
    'Гузарский межрайонный гражданский суд',
    'Gʻuzor tuman, Oʻzbekiston koʻchasi, 72-uy'),
  D('fuq-qarshi-tlf', 'kashkadarya',
    'Қарши туманлараро фуқаролик суди',
    'Qarshi tumanlararo fuqarolik sudi',
    'Каршинский межрайонный гражданский суд',
    'Qarshi shahar, Xonobod koʻchasi, 1A-uy'),
  D('fuq-kasbi-tlf', 'kashkadarya',
    'Касби туманлараро фуқаролик суди',
    'Kasbi tumanlararo fuqarolik sudi',
    'Касбинский межрайонный гражданский суд',
    'Kasbi tumani, Mugʻlon shaharchasi, Mustaqillik koʻchasi, 14-uy'),
  D('fuq-koson-tlf', 'kashkadarya',
    'Косон туманлараро фуқаролик суди',
    'Koson tumanlararo fuqarolik sudi',
    'Касанский межрайонный гражданский суд',
    'Koson tumani, Doʻstlik MFY, Mustaqillik koʻchasi, 116-uy'),
  D('fuq-chiroqchi-tlf', 'kashkadarya',
    'Чироқчи туманлараро фуқаролик суди',
    'Chiroqchi tumanlararo fuqarolik sudi',
    'Чиракчинский межрайонный гражданский суд',
    'Chiroqchi tumani, Choshtepa MFY, Dam 2 massivi, 1-uy'),
  D('fuq-shahrisabz-tlf', 'kashkadarya',
    'Шаҳрисабз туманлараро фуқаролик суди',
    'Shahrisabz tumanlararo fuqarolik sudi',
    'Шахрисабзский межрайонный гражданский суд',
    'Shahrisabz shahri, Ipak yoʻli koʻchasi, 140-uy'),
  D('fuq-yakkabog-tlf', 'kashkadarya',
    'Яккабоғ туманлараро фуқаролик суди',
    'Yakkabogʻ tumanlararo fuqarolik sudi',
    'Яккабагский межрайонный гражданский суд',
    'Yakkabogʻ tumani, A.Temur koʻchasi'),

  // ===== Қорақалпоғистон Республикаси =====
  D('fuq-kk-rsudi', 'karakalpakstan',
    'Қорақалпоғистон Республикаси суди',
    'Qoraqalpogʻiston Respublikasi sudi',
    'Верховный суд Республики Каракалпакстан',
    'Nukus shahri, Doʻstlik guzari MFY, I.Karimov koʻchasi, 122-uy'),
  D('fuq-amudaryo-tf', 'karakalpakstan',
    'Амударё туман фуқаролик суди',
    'Amudaryo tuman fuqarolik sudi',
    'Амударьинский районный гражданский суд',
    'Amudaryo tumani, Mangʻit shahar, "Doʻstlik" MFY, Gurlan koʻchasi'),
  D('fuq-beruniy-tlf', 'karakalpakstan',
    'Беруний туманлараро фуқаролик суди',
    'Beruniy tumanlararo fuqarolik sudi',
    'Берунийский межрайонный гражданский суд',
    'Beruniy tumani, Beruniy koʻchasi, raqamsiz uy'),
  D('fuq-qongirot-tlf', 'karakalpakstan',
    'Қўнғирот туманлараро фуқаролик суди',
    'Qoʻngʻirot tumanlararo fuqarolik sudi',
    'Кунградский межрайонный гражданский суд',
    'Qoʻngʻirot tumani, R.Abdullaev koʻchasi, raqamsiz uy'),
  D('fuq-nukus-tlf', 'karakalpakstan',
    'Нукус туманлараро фуқаролик суди',
    'Nukus tumanlararo fuqarolik sudi',
    'Нукусский межрайонный гражданский суд',
    'Nukus shahar, A.Dosnazarov koʻchasi, 159A-uy'),
  D('fuq-chimboy-tlf', 'karakalpakstan',
    'Чимбой туманлараро фуқаролик суди',
    'Chimboy tumanlararo fuqarolik sudi',
    'Чимбайский межрайонный гражданский суд',
    'Chimboy tumani, Doʻstlik guzari koʻchasi, raqamsiz uy'),

  // ===== Навоий вилояти =====
  D('fuq-navoi-vsudi', 'navoi',
    'Навоий вилоят суди',
    'Navoiy viloyat sudi',
    'Навоийский областной суд',
    'Navoiy shahri, Navoiy koʻchasi, 1-uy'),
  D('fuq-zarafshon-tlf', 'navoi',
    'Зарафшон туманлараро фуқаролик суди',
    'Zarafshon tumanlararo fuqarolik sudi',
    'Зарафшанский межрайонный гражданский суд',
    'Zarafshon shahri, Marvarid koʻchasi, 1-uy'),
  D('fuq-karmana-tlf', 'navoi',
    'Кармана туманлараро фуқаролик суди',
    'Karmana tumanlararo fuqarolik sudi',
    'Карманинский межрайонный гражданский суд',
    'Navoiy shahar, Navoiy koʻchasi'),
  D('fuq-navbahor-tlf', 'navoi',
    'Навбаҳор туманлараро фуқаролик суди',
    'Navbahor tumanlararo fuqarolik sudi',
    'Навбахорский межрайонный гражданский суд',
    'Navbahor tumani, Beshrabot qoʻrgʻoni, Bobur shoh koʻchasi, 7-uy'),
  D('fuq-uchquduq-tf', 'navoi',
    'Учқудуқ туман фуқаролик суди',
    'Uchquduq tuman fuqarolik sudi',
    'Учкудукский районный гражданский суд',
    'Uchquduq tumani, A.Temur koʻchasi, 46-uy'),

  // ===== Наманган вилояти =====
  D('fuq-namangan-vsudi', 'namangan',
    'Наманган вилоят суди',
    'Namangan viloyat sudi',
    'Наманганский областной суд',
    'Namangan shahri, Lutfiy koʻchasi, 6-uy'),
  D('fuq-namangan-tlf', 'namangan',
    'Наманган туманлараро фуқаролик суди',
    'Namangan tumanlararo fuqarolik sudi',
    'Наманганский межрайонный гражданский суд',
    'Namangan shahar, Margʻilon koʻchasi, 105-uy'),
  D('fuq-uchqorgon-tlf', 'namangan',
    'Учқўрғон туманлараро фуқаролик суди',
    'Uchqoʻrgʻon tumanlararo fuqarolik sudi',
    'Учкурганский межрайонный гражданский суд',
    'Uchqoʻrgʻon shahri, Nodira koʻchasi, 4-uy'),
  D('fuq-chust-tlf', 'namangan',
    'Чуст туманлараро фуқаролик суди',
    'Chust tumanlararo fuqarolik sudi',
    'Чустский межрайонный гражданский суд',
    'Chust shahri, Chustiy koʻchasi, 5-uy'),
  D('fuq-yangiqorgon-tlf', 'namangan',
    'Янгиқўрғон туманлараро фуқаролик суди',
    'Yangiqoʻrgʻon tumanlararo fuqarolik sudi',
    'Янгикурганский межрайонный гражданский суд',
    'Yangiqoʻrgʻon shahri, Chortoq koʻchasi, 15-uy'),

  // ===== Самарқанд вилояти =====
  D('fuq-samarkand-vsudi', 'samarkand',
    'Самарқанд вилоят суди',
    'Samarqand viloyat sudi',
    'Самаркандский областной суд',
    'Samarqand shahri, Mingtut koʻchasi, 2-uy'),
  D('fuq-jomboy-tlf', 'samarkand',
    'Жомбой туманлараро фуқаролик суди',
    'Jomboy tumanlararo fuqarolik sudi',
    'Джамбайский межрайонный гражданский суд',
    'Jomboy shahri, Toshkent koʻchasi, 35-uy'),
  D('fuq-ishtixon-tlf', 'samarkand',
    'Иштихон туманлараро фуқаролик суди',
    'Ishtixon tumanlararo fuqarolik sudi',
    'Иштыханский межрайонный гражданский суд',
    'Ishtixon shahri, Ishtixon koʻchasi, 11-uy'),
  D('fuq-kattaqorgon-tlf', 'samarkand',
    'Каттақўрғон туманлараро фуқаролик суди',
    'Kattaqoʻrgʻon tumanlararo fuqarolik sudi',
    'Каттакурганский межрайонный гражданский суд',
    'Kattaqoʻrgʻon tumani, Kadan qishlogʻi, Mustaqillik koʻchasi, 33-uy'),
  D('fuq-nurobod-tf', 'samarkand',
    'Нуробод туман фуқаролик суди',
    'Nurobod tuman fuqarolik sudi',
    'Нурабадский районный гражданский суд',
    'Nurobod shahri, A.Temur koʻchasi, 14-uy'),
  D('fuq-payariq-tlf', 'samarkand',
    'Пайариқ туманлараро фуқаролик суди',
    'Payariq tumanlararo fuqarolik sudi',
    'Пайарыкский межрайонный гражданский суд',
    'Payariq shahri, 50-yillik koʻchasi, 4-uy'),
  D('fuq-pastdargom-tlf', 'samarkand',
    'Пастдарғом туман фуқаролик суди',
    'Pastdargʻom tuman fuqarolik sudi',
    'Пастдаргомский районный гражданский суд',
    'Pastdargʻom tumani, Obod mahallasi'),
  D('fuq-samarkand-shahar', 'samarkand',
    'Самарқанд шаҳар фуқаролик суди',
    'Samarqand shahar fuqarolik sudi',
    'Самаркандский городской гражданский суд',
    'Samarqand shahri, A.Bahodirxon koʻchasi, 1A-uy'),
  D('fuq-tayloq-tlf', 'samarkand',
    'Тайлоқ туманлараро фуқаролик суди',
    'Tayloq tumanlararo fuqarolik sudi',
    'Тайлакский межрайонный гражданский суд',
    'Tayloq tumani, Mustaqillik koʻchasi, 8-uy'),
  D('fuq-urgut-tf', 'samarkand',
    'Ургут туман фуқаролик суди',
    'Urgut tuman fuqarolik sudi',
    'Ургутский районный гражданский суд',
    'Urgut shahar, Navoiyshoh koʻchasi, 98-uy'),

  // ===== Сирдарё вилояти =====
  D('fuq-syrdarya-vsudi', 'syrdarya',
    'Сирдарё вилоят суди',
    'Sirdaryo viloyat sudi',
    'Сырдарьинский областной суд',
    'Guliston shahar, Islom Karimov koʻchasi, 75-uy'),
  D('fuq-boyovut-tlf', 'syrdarya',
    'Боёвут туманлараро фуқаролик суди',
    'Boyovut tumanlararo fuqarolik sudi',
    'Баяутский межрайонный гражданский суд',
    'Boyovut shaharchasi, Tinchlik koʻchasi, 26-uy'),
  D('fuq-guliston-tlf', 'syrdarya',
    'Гулистон туманлараро фуқаролик суди',
    'Guliston tumanlararo fuqarolik sudi',
    'Гулистанский межрайонный гражданский суд',
    'Sirdaryo viloyati, Guliston shahar, I.Karimov koʻchasi, 1-uy'),
  D('fuq-oqoltin-tlf', 'syrdarya',
    'Оқолтин туманлараро фуқаролик суди',
    'Oqoltin tumanlararo fuqarolik sudi',
    'Акалтынский межрайонный гражданский суд',
    'Sardoba shaharchasi, Guliston koʻchasi, 7-uy'),
  D('fuq-syrdarya-tlf', 'syrdarya',
    'Сирдарё туманлараро фуқаролик суди',
    'Sirdaryo tumanlararo fuqarolik sudi',
    'Сырдарьинский межрайонный гражданский суд',
    'Sirdaryo shahar, Zavqbaxsh koʻchasi, 1A-uy'),

  // ===== Сурхондарё вилояти =====
  D('fuq-surkhandarya-vsudi', 'surkhandarya',
    'Сурхондарё вилоят суди',
    'Surxondaryo viloyat sudi',
    'Сурхандарьинский областной суд',
    'Termiz shahri, Sulton Saodat koʻchasi, 286B-uy'),
  D('fuq-boysun-tf', 'surkhandarya',
    'Бойсун туман фуқаролик суди',
    'Boysun tuman fuqarolik sudi',
    'Байсунский районный гражданский суд',
    'Boysun tumani, Olmazor koʻchasi'),
  D('fuq-denov-tlf', 'surkhandarya',
    'Денов туманлараро фуқаролик суди',
    'Denov tumanlararo fuqarolik sudi',
    'Денауский межрайонный гражданский суд',
    'Denov shahri, Ezgu maqsad koʻchasi, 63-uy'),
  D('fuq-qumqorgon-tlf', 'surkhandarya',
    'Қумқўрғон туманлараро фуқаролик суди',
    'Qumqoʻrgʻon tumanlararo fuqarolik sudi',
    'Кумкурганский межрайонный гражданский суд',
    'Qumqoʻrgʻon tumani, "Bogʻaro" mahallasi, Oʻzbekiston shoh koʻchasi, 3-uy'),
  D('fuq-sariosiyo-tlf', 'surkhandarya',
    'Сариосиё туманлараро фуқаролик суди',
    'Sariosiyo tumanlararo fuqarolik sudi',
    'Сариасийский межрайонный гражданский суд',
    'Sariosiyo tumani, Mehrshavqat mahallasi, Yoruq kun koʻchasi'),
  D('fuq-termiz-tlf', 'surkhandarya',
    'Термиз туманлараро фуқаролик суди',
    'Termiz tumanlararo fuqarolik sudi',
    'Термезский межрайонный гражданский суд',
    'Termiz shahri, Iso at-Termiziy koʻchasi, 5A-uy'),
  D('fuq-sherobod-tlf', 'surkhandarya',
    'Шеробод туманлараро фуқаролик суди',
    'Sherobod tumanlararo fuqarolik sudi',
    'Шерабадский межрайонный гражданский суд',
    'Sherobod tuman, "Doʻstlik" MFY, Mustaqillik koʻchasi, raqamsiz uy'),

  // ===== Тошкент вилояти =====
  D('fuq-tashkentreg-vsudi', 'tashkent_region',
    'Тошкент вилоят суди',
    'Toshkent viloyat sudi',
    'Ташкентский областной суд',
    'Toshkent shahar, Yakkasaroy tumani, Sh.Rustaveli koʻchasi, 93-uy'),
  D('fuq-bekobod-tlf', 'tashkent_region',
    'Бекобод туманлараро фуқаролик суди',
    'Bekobod tumanlararo fuqarolik sudi',
    'Бекабадский межрайонный гражданский суд',
    'Toshkent viloyati, Bekobod shahri, Gʻ.Gʻulom koʻchasi'),
  D('fuq-zangiota-tlf', 'tashkent_region',
    'Зангиота туманлараро фуқаролик суди',
    'Zangiota tumanlararo fuqarolik sudi',
    'Зангиатинский межрайонный гражданский суд',
    'Toshkent viloyati, Zangiota tumani, Oxunboboev koʻchasi'),
  D('fuq-quyichirchiq-tlf', 'tashkent_region',
    'Қуйичирчиқ туманлараро фуқаролик суди',
    'Quyichirchiq tumanlararo fuqarolik sudi',
    'Куйичирчикский межрайонный гражданский суд',
    'Toshkent viloyati, Quyichirchiq tumani, Doʻstlik-1 MFY, Markaziy koʻchasi'),
  D('fuq-ohangaron-tlf', 'tashkent_region',
    'Оҳангарон туманлараро фуқаролик суди',
    'Ohangaron tumanlararo fuqarolik sudi',
    'Ахангаранский межрайонный гражданский суд',
    'Toshkent viloyati, Ohangaron shahri, Ezgulik koʻchasi, 100-uy'),
  D('fuq-ortachirchiq-tlf', 'tashkent_region',
    'Ўртачирчиқ туманлараро фуқаролик суди',
    'Oʻrtachirchiq tumanlararo fuqarolik sudi',
    'Уртачирчикский межрайонный гражданский суд',
    'Toshkent viloyati, Oʻrtachirchiq tumani, Qorasuv MFY, Temirchi koʻchasi, 3A-uy'),
  D('fuq-chirchiq-tlf', 'tashkent_region',
    'Чирчиқ туманлараро фуқаролик суди',
    'Chirchiq tumanlararo fuqarolik sudi',
    'Чирчикский межрайонный гражданский суд',
    'Toshkent viloyati, Chirchiq shahri, Istiqbol koʻchasi, 8-uy'),
  D('fuq-yuqorichirchiq-tlf', 'tashkent_region',
    'Юқоричирчиқ туманлараро фуқаролик суди',
    'Yuqorichirchiq tumanlararo fuqarolik sudi',
    'Юкоричирчикский межрайонный гражданский суд',
    'Toshkent viloyati, Yuqorichirchiq tumani, Oʻrtaovul MFY, Parkent koʻchasi, 22-uy'),

  // ===== Тошкент шаҳар =====
  D('fuq-tashcity-shahar', 'tashkent_city',
    'Тошкент шаҳар суди',
    'Toshkent shahar sudi',
    'Ташкентский городской суд',
    'Toshkent shahar, Chilonzor tumani, Choʻpon-Ota koʻchasi, 6-uy'),
  D('fuq-tashcity-uchtepa-tlf', 'tashkent_city',
    'Учтепа туманлараро фуқаролик суди',
    'Uchtepa tumanlararo fuqarolik sudi',
    'Учтепинский межрайонный гражданский суд',
    'Toshkent shahar, Fozilteрa koʻchasi, 42a-uy'),
  D('fuq-tashcity-shayxontohur-tlf', 'tashkent_city',
    'Шайхонтоҳур туманлараро фуқаролик суди',
    'Shayxontohur tumanlararo fuqarolik sudi',
    'Шайхантахурский межрайонный гражданский суд',
    'Toshkent shahar, Navoiy koʻchasi, 7-uy'),
  D('fuq-tashcity-mirzo-ulugbek-tlf', 'tashkent_city',
    'Мирзо Улуғбек туманлараро фуқаролик суди',
    'Mirzo Ulugʻbek tumanlararo fuqarolik sudi',
    'Мирзо-Улугбекский межрайонный гражданский суд',
    'Toshkent shahar, Bogʻishamol koʻchasi, 57/10-uy'),
  D('fuq-tashcity-mirobod-tlf', 'tashkent_city',
    'Миробод туманлараро фуқаролик суди',
    'Mirobod tumanlararo fuqarolik sudi',
    'Миробадский межрайонный гражданский суд',
    'Toshkent shahar, Mirobod tumani, Inoqobod koʻchasi, 1-uy'),
  D('fuq-tashcity-yakkasaroy-tlf', 'tashkent_city',
    'Яккасарой туманлараро фуқаролик суди',
    'Yakkasaroy tumanlararo fuqarolik sudi',
    'Яккасарайский межрайонный гражданский суд',
    'Toshkent shahar, Yangi Sergeli koʻchasi'),

  // ===== Фарғона вилояти =====
  D('fuq-fergana-vsudi', 'fergana',
    'Фарғона вилоят суди',
    'Fargʻona viloyat sudi',
    'Ферганский областной суд',
    'Fargʻona shahri, Yangisoy koʻchasi, 2-uy'),
  D('fuq-qoqon-tlf', 'fergana',
    'Қўқон туманлараро фуқаролик суди',
    'Qoʻqon tumanlararo fuqarolik sudi',
    'Кокандский межрайонный гражданский суд',
    'Qoʻqon shahri, Imom Buxoriy koʻchasi, 37-uy'),
  D('fuq-margilon-tlf', 'fergana',
    'Марғилон туманлараро фуқаролик суди',
    'Margʻilon tumanlararo fuqarolik sudi',
    'Маргиланский межрайонный гражданский суд',
    'Margʻilon shahri, Nurafshon koʻchasi, 7-uy'),
  D('fuq-rishton-tlf', 'fergana',
    'Риштон туманлараро фуқаролик суди',
    'Rishton tumanlararo fuqarolik sudi',
    'Риштанский межрайонный гражданский суд',
    'Rishton tumani, Markaz MFY, B.Roshidoniy koʻchasi, 187A-uy'),
  D('fuq-ozbekiston-tlf', 'fergana',
    'Ўзбекистон туманлараро фуқаролик суди',
    'Oʻzbekiston tumanlararo fuqarolik sudi',
    'Узбекистанский межрайонный гражданский суд',
    'Oʻzbekiston tumani, Konizar qishlogʻi, A.Navoiy koʻchasi, 18-uy'),
  D('fuq-fergana-tlf', 'fergana',
    'Фарғона туманлараро фуқаролик суди',
    'Fargʻona tumanlararo fuqarolik sudi',
    'Ферганский межрайонный гражданский суд',
    'Fargʻona shahri, Xoʻjand koʻchasi, 12A-uy'),
  D('fuq-sox-tf', 'fergana',
    'Сўх туман фуқаролик суди',
    'Soʻx tuman fuqarolik sudi',
    'Сохский районный гражданский суд',
    'Soʻx tumani, Ravon MFY, A.Temur koʻchasi, 187-uy'),

  // ===== Хоразм вилояти =====
  D('fuq-khorezm-vsudi', 'khorezm',
    'Хоразм вилоят суди',
    'Xorazm viloyat sudi',
    'Хорезмский областной суд',
    'Urganch shahri, Mashʼal koʻchasi, 3-uy'),
  D('fuq-bogot-tlf', 'khorezm',
    'Боғот туманлараро фуқаролик суди',
    'Bogʻot tumanlararo fuqarolik sudi',
    'Багатский межрайонный гражданский суд',
    'Bogʻot tumani, Navroʻz koʻchasi, 104-uy'),
  D('fuq-urganch-tlf', 'khorezm',
    'Урганч туманлараро фуқаролик суди',
    'Urganch tumanlararo fuqarolik sudi',
    'Ургенчский межрайонный гражданский суд',
    'Urganch shahri, Mashʼal koʻchasi, 3-uy'),
  D('fuq-shovot-tlf', 'khorezm',
    'Шовот туманлараро фуқаролик суди',
    'Shovot tumanlararo fuqarolik sudi',
    'Шаватский межрайонный гражданский суд',
    'Shovot tumani, Turkiston koʻchasi, 3-uy'),

];

/* =====================================================================
 * MAMURIY (administrative) courts — authoritative MySud (mysud.uz) data.
 * Each region has exactly two courts: the regional appellate court and
 * a single inter-district court at the regional centre. Karakalpakstan
 * uses "Republic" + "Nukus inter-district" instead of "regional" naming.
 * ===================================================================== */
const MAMURIY_COURTS: DistrictCourtDef[] = [
  // ===== Andijon =====
  M('mam-andijan-vsudi', 'andijan',
    'Андижон вилоят маъмурий суди',
    'Andijon shahar, Bobur shox koʻchasi, 26-uy'),
  M('mam-andijan-tlms', 'andijan',
    'Андижон туманлараро маъмурий суди',
    'Andijon shahar, Bobur shox koʻchasi, 26-uy'),

  // ===== Bukhara =====
  M('mam-bukhara-vsudi', 'bukhara',
    'Бухоро вилоят маъмурий суди',
    'Buxoro shahri, Yangiobod koʻchasi, 29-uy'),
  M('mam-bukhara-tlms', 'bukhara',
    'Бухоро туманлараро маъмурий суди',
    'Buxoro shahri, Yangiobod koʻchasi, 29-uy'),

  // ===== Jizzakh =====
  M('mam-jizzakh-vsudi', 'jizzakh',
    'Жиззах вилоят маъмурий суди',
    'Jizzax shahar, M.Tursunov koʻchasi, 1-uy'),
  M('mam-jizzakh-tlms', 'jizzakh',
    'Жиззах туманлараро маъмурий суди',
    'Sh.Rashidov tumani, Uchtepa dahasi, Paxtakor koʻchasi'),

  // ===== Kashkadarya =====
  M('mam-qash-vsudi', 'kashkadarya',
    'Қашқадарё вилоят маъмурий суди',
    'Qarshi shahri, A.Oripov koʻchasi, 7-uy'),
  M('mam-qarshi-tlms', 'kashkadarya',
    'Қарши туманлараро маъмурий суди',
    'Qarshi shahri, A.Oripov koʻchasi, 7-uy'),

  // ===== Karakalpakstan =====
  M('mam-kk-rsudi', 'karakalpakstan',
    'Қорақалпоғистон Республикаси маъмурий суди',
    'Nukus shahar, Chimboy guzari koʻchasi, 37-uy'),
  M('mam-nukus-tlms', 'karakalpakstan',
    'Нукус туманлараро маъмурий суди',
    'Nukus shahar, Botanika bogʻi MFY, Chimboy guzari, 37-uy'),

  // ===== Navoi =====
  M('mam-navoi-vsudi', 'navoi',
    'Навоий вилоят маъмурий суди',
    'Navoiy viloyati, Navoiy shahar, Sadriddin Ayniy koʻchasi, 1-uy'),
  M('mam-navoi-tlms', 'navoi',
    'Навоий туманлараро маъмурий суди',
    'Navoiy shahar, S.Ayniy koʻchasi, 1-uy'),

  // ===== Namangan =====
  M('mam-namangan-vsudi', 'namangan',
    'Наманган вилоят маъмурий суди',
    'Namangan shahar, Lutfiy koʻchasi, 6-uy'),
  M('mam-namangan-tlms', 'namangan',
    'Наманган туманлараро маъмурий суди',
    'Namangan shahar, Lutfiy koʻchasi, 6-uy'),

  // ===== Samarkand =====
  M('mam-samarkand-vsudi', 'samarkand',
    'Самарқанд вилоят маъмурий суди',
    'Samarqand shahri, Koʻksaroy maydoni koʻchasi, 3-uy'),
  M('mam-samarkand-tlms', 'samarkand',
    'Самарқанд туманлараро маъмурий суди',
    'Samarqand shahar, Koʻksaroy maydoni, 3-uy'),

  // ===== Syrdarya =====
  M('mam-syrdarya-vsudi', 'syrdarya',
    'Сирдарё вилоят маъмурий суди',
    'Guliston shahar, Oʻzbekiston shoh koʻchasi, 68-uy'),
  M('mam-guliston-tlms', 'syrdarya',
    'Гулистон туманлараро маъмурий суди',
    'Guliston shahar, Oʻzbekiston shoh koʻchasi, 68-uy'),

  // ===== Surkhandarya =====
  M('mam-surkhandarya-vsudi', 'surkhandarya',
    'Сурхондарё вилоят маъмурий суди',
    'Termiz shahar, Navbogʻ koʻchasi, 12-uy'),
  M('mam-termiz-tlms', 'surkhandarya',
    'Термиз туманлараро маъмурий суди',
    'Termiz shahar, Sh.Rashidov koʻchasi, 67-uy'),

  // ===== Tashkent region =====
  M('mam-tashreg-vsudi', 'tashkent_region',
    'Тошкент вилоят маъмурий суди',
    'Toshkent shahar, Usmon Nosir koʻchasi, 93-uy'),
  M('mam-nurafshon-tlms', 'tashkent_region',
    'Нурафшон туманлараро маъмурий суди',
    'Nurafshon shahar, Toshkent yoʻli koʻchasi, 248-uy'),

  // ===== Tashkent city =====
  M('mam-tashcity-shahar', 'tashkent_city',
    'Тошкент шаҳар маъмурий суди',
    'Toshkent shahri, Yunusobod tumani, Amir Temur koʻchasi, 118A-uy'),
  M('mam-tashcity-tlms', 'tashkent_city',
    'Тошкент туманлараро маъмурий суди',
    'Chilonzor tumani, Sharq tongi koʻchasi, 1A-uy; Shayxontohur tumani, Beruniy koʻchasi, 3/4-uy'),

  // ===== Fergana =====
  M('mam-fergana-vsudi', 'fergana',
    'Фарғона вилоят маъмурий суди',
    'Fargʻona shahri, Al-Fargʻoniy koʻchasi, 47-uy'),
  M('mam-fergana-tlms', 'fergana',
    'Фарғона туманлараро маъмурий суди',
    'Fargʻona shahar, Al-Fargʻoniy koʻchasi, 47-uy'),

  // ===== Khorezm =====
  M('mam-khorezm-vsudi', 'khorezm',
    'Хоразм вилоят маъмурий суди',
    'Urganch shahri, Al-Xorazmiy koʻchasi, 95-uy'),
  M('mam-urganch-tlms', 'khorezm',
    'Урганч туманлараро маъмурий суди',
    'Urganch shahar, Al-Xorazmiy koʻchasi, 95-uy'),
];

/* =====================================================================
 * IQTISODIY (economic) courts — authoritative MySud data. Each region
 * has a regional appellate court (X вилоят суди / Республика суди) plus
 * several inter-district economic courts. Toshkent shahar has the city
 * court acting as appellate panel.
 * ===================================================================== */
const IQTISODIY_COURTS: DistrictCourtDef[] = [
  // ===== Andijon =====
  I('iqt-andijan-vsudi', 'andijan',
    'Андижон вилоят суди',
    'Andijon shahar, A.Navoiy shoh koʻchasi, 15-uy'),
  I('iqt-andijan-tlmis', 'andijan',
    'Андижон туманлараро иқтисодий суди',
    'Andijon shahar, A.Navoiy shoh koʻchasi, 41-uy'),
  I('iqt-asaka-tlmis', 'andijan',
    'Асака туманлараро иқтисодий суди',
    'Asaka shahri, Sohilboʻyi koʻchasi, 11-uy'),
  I('iqt-boston-tlmis', 'andijan',
    'Бўстон туманлараро иқтисодий суди',
    'Boʻston tumani, Pillakor MFY, Mustaqillik koʻchasi, 32-uy'),
  I('iqt-izboskan-tlmis', 'andijan',
    'Избоскан туманлараро иқтисодий суди',
    'Izboskan tumani, Poytugʻ shahri, Mirzo Ulugʻbek koʻchasi, 2-uy'),
  I('iqt-qorgontepa-tlmis', 'andijan',
    'Қўрғонтепа туманлараро иқтисодий суди',
    'Qoʻrgʻontepa shahri, Mustaqillik koʻchasi, 50-a uy'),
  I('iqt-xojaobod-tlmis', 'andijan',
    'Хўжаобод туманлараро иқтисодий суди',
    'Xoʻjaobod shahri, Pok niyat koʻchasi, 2-uy'),

  // ===== Bukhara =====
  I('iqt-bukhara-vsudi', 'bukhara',
    'Бухоро вилоят суди',
    'Buxoro shahar, Yangi hayot koʻchasi, 122-uy'),
  I('iqt-bukhara-tlmis', 'bukhara',
    'Бухоро туманлараро иқтисодий суди',
    'Buxoro tumani, Gʻala Osiyo shahri, Buyuk ipak yoʻli koʻchasi'),
  I('iqt-kogon-tlmis', 'bukhara',
    'Когон туманлараро иқтисодий суди',
    'Kogon shahar, Qorovulbozor shoh koʻchasi, 2-uy'),
  I('iqt-gijduvon-tlmis', 'bukhara',
    'Ғиждувон туманлараро иқтисодий суди',
    'Gʻijduvon tuman, Yu.Hamadoniy koʻchasi, 54-uy'),
  I('iqt-qorakul-tlmis', 'bukhara',
    'Қоракўл туманлараро иқтисодий суди',
    'Qoraqoʻl tumani, Buxoro koʻchasi, 152-uy'),
  I('iqt-peshku-tlmis', 'bukhara',
    'Пешку туманлараро иқтисодий суди',
    'Peshku tumani, A.Temur koʻchasi, 5-uy'),

  // ===== Jizzakh =====
  I('iqt-jizzakh-vsudi', 'jizzakh',
    'Жиззах вилоят суди',
    'Jizzax shahri, Katta uzbek trakti, 115-uy'),
  I('iqt-jizzakh-tlmis', 'jizzakh',
    'Жиззах туманлараро иқтисодий суди',
    'Jizzax shahri, Katta uzbek trakti, 115-uy'),
  I('iqt-forish-tis', 'jizzakh',
    'Фориш туман иқтисодий суди',
    'Forish tumani, Osmonsoy QFY, Tutak qishlogʻi'),
  I('iqt-gallaorol-tlmis', 'jizzakh',
    'Ғаллаорол туманлараро иқтисодий суди',
    'Gʻallaorol tumani, Sarbozor MFY, Shodlik koʻchasi, 17-uy'),
  I('iqt-dustlik-tlmis', 'jizzakh',
    'Дўстлик туманлараро иқтисодий суди',
    'Doʻstlik tumani, Doʻstlik shahar, Alisher Navoiy MFY'),
  I('iqt-zomin-tlmis', 'jizzakh',
    'Зомин туманлараро иқтисодий суди',
    'Zomin tumani, Shirin QFY, Nebosa qishlogʻi'),

  // ===== Kashkadarya =====
  I('iqt-qash-vsudi', 'kashkadarya',
    'Қашқадарё вилоят суди',
    'Qarshi shahar, A.Oripov koʻchasi, 10A-uy'),
  I('iqt-qarshi-tlmis', 'kashkadarya',
    'Қарши туманлараро иқтисодий суди',
    'Qarshi shahar, Bogʻzor koʻchasi, 2-A uy'),
  I('iqt-shahrisabz-tlmis', 'kashkadarya',
    'Шаҳрисабз туманлараро иқтисодий суди',
    'Shahrisabz shahri, Ipak yoʻli koʻchasi, 140-uy'),
  I('iqt-koson-tlmis', 'kashkadarya',
    'Косон туманлараро иқтисодий суди',
    'Koson tumani, Mustaqillik koʻchasi, 116-uy'),
  I('iqt-kasbi-tlmis', 'kashkadarya',
    'Касби туманлараро иқтисодий суди',
    'Kasbi tumani, Mugʻlon koʻchasi'),
  I('iqt-chiroqchi-tis', 'kashkadarya',
    'Чироқчи туман иқтисодий суди',
    'Chiroqchi tumani, Dam-2 massivi, 1-uy'),
  I('iqt-guzor-tlmis', 'kashkadarya',
    'Ғузор туманлараро иқтисодий суди',
    'Qarshi shahar, Bogʻzor koʻchasi, 2-A uy'),
  I('iqt-yakkabog-tlmis', 'kashkadarya',
    'Яккабоғ туманлараро иқтисодий суди',
    'Yakkabogʻ shahri, Aygʻirkoʻl MFY, Amir Temur koʻchasi'),

  // ===== Karakalpakstan =====
  I('iqt-kk-rsudi', 'karakalpakstan',
    'Қорақалпоғистон Республикаси суди',
    'Nukus shahri, Doʻstlik guzari MFY, I.Karimov koʻchasi, 122-uy'),
  I('iqt-nukus-tlmis', 'karakalpakstan',
    'Нукус туманлараро иқтисодий суди',
    'Nukus shahri, A.Dosnazarov koʻchasi, 92-uy'),
  I('iqt-chimboy-tlmis', 'karakalpakstan',
    'Чимбой туманлараро иқтисодий суди',
    'Chimboy tumani, Tozgora OFY, raqamsiz uy'),
  I('iqt-qongirot-tlmis', 'karakalpakstan',
    'Қўнғирот туманлараро иқтисодий суди',
    'Qoʻngʻirot tumani, R.Abdullaev koʻchasi, raqamsiz uy'),
  I('iqt-beruniy-tlmis', 'karakalpakstan',
    'Беруний туманлараро иқтисодий суди',
    'Beruniy tumani, Beruniy koʻchasi, raqamsiz uy'),

  // ===== Navoi =====
  I('iqt-navoi-vsudi', 'navoi',
    'Навоий вилоят суди',
    'Navoiy shahar, Navoiy koʻchasi, 1-uy'),
  I('iqt-karmana-tlmis', 'navoi',
    'Кармана туманлараро иқтисодий суди',
    'Navoiy shahar, Navoiy koʻchasi, 39 b-uy'),
  I('iqt-zarafshon-tlmis', 'navoi',
    'Зарафшон туманлараро иқтисодий суди',
    'Zarafshon shahar, Marvarid koʻchasi, 19-uy'),
  I('iqt-navbahor-tlmis', 'navoi',
    'Навбаҳор туманлараро иқтисодий суди',
    'Navbahor tumani, Bobur shoh koʻchasi, 7-uy'),
  I('iqt-uchquduq-tis', 'navoi',
    'Учқудуқ туман иқтисодий суди',
    'Uchquduq tumani, Amir Temur koʻchasi, 46-uy'),

  // ===== Namangan =====
  I('iqt-namangan-vsudi', 'namangan',
    'Наманган вилоят суди',
    'Namangan shahri, N.Namangoniy koʻchasi, 20a-uy'),
  I('iqt-namangan-tlmis', 'namangan',
    'Наманган туманлараро иқтисодий суди',
    'Namangan shahri, N.Namangoniy koʻchasi, 20a-uy'),
  I('iqt-yangiqorgon-tlmis', 'namangan',
    'Янгиқўрғон туманлараро иқтисодий суди',
    'Yangiqoʻrgʻon shaharchasi, Chortoq koʻchasi, 15-uy'),
  I('iqt-uchqorgon-tlmis', 'namangan',
    'Учқўрғон туманлараро иқтисодий суди',
    'Uchqoʻrgʻon shahri, Nodira koʻchasi, 4-uy'),
  I('iqt-chust-tlmis', 'namangan',
    'Чуст туманлараро иқтисодий суди',
    'Chust shahri, Chustiy koʻchasi, 5-uy'),

  // ===== Samarkand =====
  I('iqt-samarkand-vsudi', 'samarkand',
    'Самарқанд вилоят суди',
    'Samarqand shahri, Mingtut koʻchasi, 2-uy'),
  I('iqt-samarkand-shahar', 'samarkand',
    'Самарқанд шаҳар иқтисодий суди',
    'Samarqand shahri, Mingtut koʻchasi, 2-uy'),
  I('iqt-kattaqorgon-tlmis', 'samarkand',
    'Каттақўрғон туманлараро иқтисодий суди',
    'Kattaqoʻrgʻon tumani, Kadan q., Mustaqillik koʻchasi, 34-uy'),
  I('iqt-ishtixon-tlmis', 'samarkand',
    'Иштихон туманлараро иқтисодий суди',
    'Ishtixon sh., Ishtixon koʻchasi, 11-uy'),
  I('iqt-jomboy-tlmis', 'samarkand',
    'Жомбой туманлараро иқтисодий суди',
    'Jomboy sh., Toshkent koʻchasi, 35-uy'),
  I('iqt-tayloq-tlmis', 'samarkand',
    'Тайлоқ туманлараро иқтисодий суди',
    'Tayloq tumani, Mustaqillik koʻchasi, 8-uy'),
  I('iqt-payariq-tlmis', 'samarkand',
    'Пайариқ туманлараро иқтисодий суди',
    'Payariq sh., 50 yillik koʻchasi, 4-uy'),
  I('iqt-pastdargom-tlmis', 'samarkand',
    'Пастдарғом туманлараро иқтисодий суди',
    'Pastdargʻom tumani, Goʻzalkent qoʻrgʻoni'),

  // ===== Syrdarya =====
  I('iqt-syrdarya-vsudi', 'syrdarya',
    'Сирдарё вилоят суди',
    'Guliston shahri, Islom Karimov koʻchasi, 75-uy'),
  I('iqt-guliston-tlmis', 'syrdarya',
    'Гулистон туманлараро иқтисодий суди',
    'Guliston shahar, Birlashgan koʻchasi, 7-uy'),
  I('iqt-syrdarya-tlmis', 'syrdarya',
    'Сирдарё туманлараро иқтисодий суди',
    'Sirdaryo shahar, Oʻzbekiston koʻchasi, 80-uy'),
  I('iqt-boyovut-tlmis', 'syrdarya',
    'Боёвут туманлараро иқтисодий суди',
    'Hovos shahar, Fidokorlar koʻchasi, 16-uy'),
  I('iqt-oqoltin-tlmis', 'syrdarya',
    'Оқолтин туманлараро иқтисодий суди',
    'Sardoba shaharchasi, Guliston koʻchasi, 7-uy'),

  // ===== Surkhandarya =====
  I('iqt-surkhandarya-vsudi', 'surkhandarya',
    'Сурхондарё вилоят суди',
    'Termiz shahri, Sulton saodat koʻchasi, 286 b-uy'),
  I('iqt-termiz-tlmis', 'surkhandarya',
    'Термиз туманлараро иқтисодий суди',
    'Termiz shahri, Sh.Rashidov koʻchasi, 67-uy'),
  I('iqt-sariosiyo-tlmis', 'surkhandarya',
    'Сариосиё туманлараро иқтисодий суди',
    'Sariosiyo tumani, Mehr shavqat mahallasi'),
  I('iqt-sherobod-tlmis', 'surkhandarya',
    'Шеробод туманлараро иқтисодий суди',
    'Sherobod tumani, "Doʻstlik" mahallasi, Mustaqillik koʻchasi'),
  I('iqt-qumqorgon-tlmis', 'surkhandarya',
    'Қумқўрғон туманлараро иқтисодий суди',
    'Qumqoʻrgʻon tumani, Bogʻaro mahallasi, Oʻzbekiston shoh koʻchasi'),
  I('iqt-denov-tlmis', 'surkhandarya',
    'Денов туманлараро иқтисодий суди',
    'Denov tumani, Buyuk kelajak MFY, Ezgu maqsad koʻchasi, 63-uy'),

  // ===== Tashkent region =====
  I('iqt-tashreg-vsudi', 'tashkent_region',
    'Тошкент вилоят суди',
    'Toshkent shahar, Usmon Nosir koʻchasi, 93-uy'),
  I('iqt-zangiota-tlmis', 'tashkent_region',
    'Зангиота туманлараро иқтисодий суди',
    'Toshkent viloyati, Zangiota tumani, Eshonguzar MFY, Y.Oxunboboyev koʻchasi'),
  I('iqt-chirchiq-tlmis', 'tashkent_region',
    'Чирчиқ туманлараро иқтисодий суди',
    'Toshkent viloyati, Chirchiq shahri, Istiqbol koʻchasi, 8-uy'),
  I('iqt-quyichirchiq-tlmis', 'tashkent_region',
    'Қуйичирчиқ туманлараро иқтисодий суди',
    'Toshkent viloyati, Qoʻyichirchiq tumani, Doʻstobod shahar, "Doʻstlik-1" MFY, Markaziy koʻchasi'),
  I('iqt-ortachirchiq-tlmis', 'tashkent_region',
    'Ўртачирчиқ туманлараро иқтисодий суди',
    'Toshkent viloyati, Oʻrtachirchiq tumani, Qorasuv qoʻrgʻoni, Temirchi koʻchasi, 3-uy'),
  I('iqt-yuqorichirchiq-tlmis', 'tashkent_region',
    'Юқоричирчиқ туманлараро иқтисодий суди',
    'Toshkent viloyati, Yuqorichirchiq tumani, Yangibozor qoʻrgʻoni, Mustaqillik koʻchasi, 77-uy'),
  I('iqt-bekobod-tlmis', 'tashkent_region',
    'Бекобод туманлараро иқтисодий суди',
    'Toshkent viloyati, Bekobod shahar, Gʻ.Gʻulom koʻchasi'),
  I('iqt-ohangaron-tlmis', 'tashkent_region',
    'Оҳангарон туманлараро иқтисодий суди',
    'Toshkent viloyati, Ohangaron shahri, Ezgulik koʻchasi, 100-uy'),

  // ===== Tashkent city =====
  I('iqt-tashcity-shahar', 'tashkent_city',
    'Тошкент шаҳар суди',
    'Toshkent shahar, Choʻpon-ota koʻchasi, 6-uy'),
  I('iqt-tashcity-tlmis', 'tashkent_city',
    'Тошкент туманлараро иқтисодий суди',
    'Toshkent shahar, Choʻpon-ota koʻchasi, 6-uy'),

  // ===== Fergana =====
  I('iqt-fergana-vsudi', 'fergana',
    'Фарғона вилоят суди',
    'Fargʻona shahri, Yangisoy koʻchasi, 2-uy'),
  I('iqt-fergana-tlmis', 'fergana',
    'Фарғона туманлараро иқтисодий суди',
    'Fargʻona shahri, Al-Fargʻoniy koʻchasi, 47-uy'),
  I('iqt-qoqon-tlmis', 'fergana',
    'Қўқон туманлараро иқтисодий суди',
    'Qoʻqon shahar, Imom Buxoriy koʻchasi, 37a-uy'),
  I('iqt-ozbekiston-tlmis', 'fergana',
    'Ўзбекистон туманлараро иқтисодий суди',
    'Oʻzbekiston tumani, Konizar qishlogʻi, A.Navoiy koʻchasi, 18-uy'),
  I('iqt-margilon-tlmis', 'fergana',
    'Марғилон туманлараро иқтисодий суди',
    'Margʻilon shahar, Nurafshon koʻchasi, 7-uy'),
  I('iqt-rishton-tlmis', 'fergana',
    'Риштон туманлараро иқтисодий суди',
    'Rishton tumani, B.Roshidoniy koʻchasi, 187a-uy'),

  // ===== Khorezm =====
  I('iqt-khorezm-vsudi', 'khorezm',
    'Хоразм вилоят суди',
    'Urganch shahar, Mashʼal koʻchasi, 4-uy'),
  I('iqt-urganch-tlmis', 'khorezm',
    'Урганч туманлараро иқтисодий суди',
    'Urganch shahar, Mashʼal koʻchasi, 3-uy'),
  I('iqt-shovot-tlmis', 'khorezm',
    'Шовот туманлараро иқтисодий суди',
    'Shovot tumani, Turkiston koʻchasi, 3-uy'),
  I('iqt-bogot-tlmis', 'khorezm',
    'Боғот туманлараро иқтисодий суди',
    'Bogʻot tumani, Navroʻz koʻchasi, 104-uy'),
];

/* =====================================================================
 * JINOYAT (criminal) courts — authoritative MySud data. Each region has
 * one regional appellate court ("X вилояти суди") plus city/district
 * criminal courts. Names are kept SHORT (without "Жиноят ишлари бўйича"
 * prefix), so the existing jinoyat document templates that prepend that
 * phrase keep rendering correctly.
 * ===================================================================== */
const JINOYAT_COURTS: DistrictCourtDef[] = [
  // ===== Andijon =====
  J('jin-andijan-vsudi', 'andijan',
    'Андижон вилояти суди',
    'Andijon shahar, Alisher Navoiy shoh koʻchasi, 15-uy'),
  J('jin-andijan-shahar', 'andijan',
    'Андижон шаҳар суди',
    'Andijon shahar, Toshkent koʻchasi, 4-uy'),
  J('jin-andijan-tuman', 'andijan',
    'Андижон туман суди',
    'Andijon tuman, Sanoat MFY, Oltin vodiy koʻchasi, 4-uy'),
  J('jin-asaka-tuman', 'andijan',
    'Асака туман суди',
    'Asaka tumani, Sohil boʻyi koʻchasi, 11-uy'),
  J('jin-baliqchi-tuman', 'andijan',
    'Балиқчи туман суди',
    'Baliqchi tuman, Andijon koʻchasi, 1-uy'),
  J('jin-buloqboshi-tuman', 'andijan',
    'Булоқбоши туман суди',
    'Buloqboshi tuman, Uzumzor koʻchasi, 162-uy'),
  J('jin-boz-tuman', 'andijan',
    'Бўз туман суди',
    'Boʻz tuman, Mustaqillik koʻchasi, 36-uy'),
  J('jin-izboskan-tuman', 'andijan',
    'Избоскан туман суди',
    'Izboskan tuman, J.Siddikov koʻchasi, 3-uy'),
  J('jin-jalaquduq-tuman', 'andijan',
    'Жалақудуқ туман суди',
    'Jalaquduq tumani, Tuyalas MFY, Mashriq koʻchasi, 2-uy'),
  J('jin-marhamat-tuman', 'andijan',
    'Марҳамат туман суди',
    'Marxamat tumani, Mustaqillik koʻchasi, 33-uy'),
  J('jin-oltinkol-tuman', 'andijan',
    'Олтинкўл туман суди',
    'Oltinkoʻl tuman, Chinobod shox koʻchasi, 15-uy'),
  J('jin-paxtaobod-tuman', 'andijan',
    'Пахтаобод туман суди',
    'Paxtaobod tuman, Muazzimboy koʻchasi, 1-uy'),
  J('jin-qorgontepa-tuman', 'andijan',
    'Қўрғонтепа туман суди',
    'Qoʻrgʻontepa tuman, Mustaqillik koʻchasi, 50-uy'),
  J('jin-ulugnor-tuman', 'andijan',
    'Улуғнор туман суди',
    'Ulugʻnor tumani, Mustaqillik koʻchasi, 3-uy'),
  J('jin-xojaobod-tuman', 'andijan',
    'Хўжаобод туман суди',
    'Xoʻjaobod tuman, Uzun koʻchasi, 2-uy'),
  J('jin-xonobod-shahar', 'andijan',
    'Хонобод шаҳар суди',
    'Xonobod shahar, Bogʻibaland koʻchasi, 1-uy'),
  J('jin-shaxrixon-tuman', 'andijan',
    'Шаҳрихон туман суди',
    'Shaxrixon tuman, R.Yodgorov koʻchasi, 3-uy'),

  // ===== Bukhara =====
  J('jin-bukhara-vsudi', 'bukhara',
    'Бухоро вилояти суди',
    'Buxoro shahar, Hofiz Tonish Buxoriy koʻchasi, 13-uy'),
  J('jin-bukhara-shahar', 'bukhara',
    'Бухоро шаҳар суди',
    'Buxoro shahar, I.Moʻminov koʻchasi, 28-uy'),
  J('jin-bukhara-tuman', 'bukhara',
    'Бухоро туман суди',
    'Buxoro tumani, Bahor koʻchasi, 25-uy'),
  J('jin-gijduvon-tuman', 'bukhara',
    'Ғиждувон туман суди',
    'Gʻijduvon shahar, Mustaqillik koʻchasi, 2-uy'),
  J('jin-jondor-tuman', 'bukhara',
    'Жондор туман суди',
    'Jondor tuman, M.Tarobiy koʻchasi, 2-uy'),
  J('jin-kogon-shahar', 'bukhara',
    'Когон шаҳар суди',
    'Kogon shahar, Qorovulbozor shoh koʻchasi, 2-uy'),
  J('jin-kogon-tuman', 'bukhara',
    'Когон туман суди',
    'Kogon shahar, Qorovulbozor shoh koʻchasi, 2-uy'),
  J('jin-olot-tuman', 'bukhara',
    'Олот туман суди',
    'Olot shahar, Olot koʻchasi, 147-uy'),
  J('jin-peshku-tuman', 'bukhara',
    'Пешку туман суди',
    'Peshku tumani, A.Temur koʻchasi, 5-uy'),
  J('jin-qorakul-tuman', 'bukhara',
    'Қоракўл туман суди',
    'Qorakoʻl shahri, Toshkent koʻchasi, 28-uy'),
  J('jin-qorovulbozor-tuman', 'bukhara',
    'Қоровулбозор туман суди',
    'Qorovulbozor tumani, Nodira koʻchasi, 10-uy'),
  J('jin-romitan-tuman', 'bukhara',
    'Ромитан туман суди',
    'Romitan shahar, A.Temur koʻchasi, 44-uy'),
  J('jin-shofirkon-tuman', 'bukhara',
    'Шофиркон туман суди',
    'Shofirkon tumani, Sultonobod koʻchasi, 3-uy'),
  J('jin-vobkent-tuman', 'bukhara',
    'Вобкент туман суди',
    'Vobkent shahri, F.Xoʻjaev koʻchasi, 21-uy'),

  // ===== Jizzakh =====
  J('jin-jizzakh-vsudi', 'jizzakh',
    'Жиззах вилояти суди',
    'Jizzax shahri, Sayiljoyi koʻchasi, 63-uy'),
  J('jin-jizzakh-shahar', 'jizzakh',
    'Жиззах шаҳар суди',
    'Jizzax shahri, O.Azimov koʻchasi, 7-uy'),
  J('jin-arnasoy-tuman', 'jizzakh',
    'Арнасой туман суди',
    'Arnasoy tumani, Gʻoliblar ShFY, Alpomish koʻchasi, 60-uy'),
  J('jin-baxmal-tuman', 'jizzakh',
    'Бахмал туман суди',
    'Baxmal tumani, Oʻsmat shaharchasi, Mustaqillik koʻchasi, 1-uy'),
  J('jin-dustlik-tuman', 'jizzakh',
    'Дўстлик туман суди',
    'Doʻstlik shaharchasi, Doʻstlik koʻchasi, 15-uy'),
  J('jin-forish-tuman', 'jizzakh',
    'Фориш туман суди',
    'Forish tumani, Bogʻdon shaxarchasi, Fayzobod koʻchasi'),
  J('jin-gallaorol-tuman', 'jizzakh',
    'Ғаллаорол туман суди',
    'Gʻallaorol tumani, Sarbozor qoʻrgʻoni'),
  J('jin-mirzachol-tuman', 'jizzakh',
    'Мирзачўл туман суди',
    'Mirzachoʻl tumani, Gagarin shahri, Gʻalaba MFY, Gagarin koʻchasi, 7-uy'),
  J('jin-paxtakor-tuman', 'jizzakh',
    'Пахтакор туман суди',
    'Paxtakor shahri, Y.Rajabiy koʻchasi, 1-uy'),
  J('jin-rashidov-tuman', 'jizzakh',
    'Ш.Рашидов туман суди',
    'Sh.Rashidov tumani, Uchtepa dahasi, Paxtakor koʻchasi'),
  J('jin-yangiobod-tuman', 'jizzakh',
    'Янгиобод туман суди',
    'Yangiobod shaharchasi, Mustaqillik koʻchasi, 4-uy'),
  J('jin-zafarobod-tuman', 'jizzakh',
    'Зафаробод туман суди',
    'Zafarobod tumani, A.Navoiy koʻchasi, 1-uy'),
  J('jin-zarbdor-tuman', 'jizzakh',
    'Зарбдор туман суди',
    'Zarbdor tumani, Mustaqillik shoh koʻchasi, raqamsiz uy'),
  J('jin-zomin-tuman', 'jizzakh',
    'Зомин туман суди',
    'Zomin shahar, A.Sattarov koʻchasi, 1-uy'),

  // ===== Kashkadarya =====
  J('jin-qash-vsudi', 'kashkadarya',
    'Қашқадарё вилояти суди',
    'Qarshi shahar, Nurbogʻ koʻchasi, 97-uy'),
  J('jin-qarshi-shahar', 'kashkadarya',
    'Қарши шаҳар суди',
    'Qarshi shahar, Nurbogʻ koʻchasi, 41-uy'),
  J('jin-qarshi-tuman', 'kashkadarya',
    'Қарши туман суди',
    'Qarshi tuman, Beshket shahri, Mustaqillik koʻchasi, 18-uy'),
  J('jin-shahrisabz-shahar', 'kashkadarya',
    'Шаҳрисабз шаҳар суди',
    'Shahrisabz shahar, Ipak yoʻli koʻchasi, 158-uy'),
  J('jin-shahrisabz-tuman', 'kashkadarya',
    'Шаҳрисабз туман суди',
    'Shahrisabz shahar, Ipak yoʻli koʻchasi, 158-uy'),
  J('jin-chiroqchi-tuman', 'kashkadarya',
    'Чироқчи туман суди',
    'Chiroqchi tuman, Mustaqillik koʻchasi, 7-uy'),
  J('jin-dehqonobod-tuman', 'kashkadarya',
    'Деҳқонобод туман суди',
    'Dehqonobod tuman, Qorashina saharchasi, M.Ulugʻbek koʻchasi, 3-uy'),
  J('jin-guzor-tuman', 'kashkadarya',
    'Ғузор туман суди',
    'Gʻuzor tuman, Oʻzbekiston koʻchasi, 72-uy'),
  J('jin-kasbi-tuman', 'kashkadarya',
    'Касби туман суди',
    'Kasbi tuman, Mugʻlon shaharchasi'),
  J('jin-kitob-tuman', 'kashkadarya',
    'Китоб туман суди',
    'Kitob tuman, Katta yoʻl koʻchasi'),
  J('jin-koson-tuman', 'kashkadarya',
    'Косон туман суди',
    'Koson tuman, Mustaqillik shoh koʻchasi'),
  J('jin-kokdala-tuman', 'kashkadarya',
    'Кўкдала туман суди',
    'Koʻkdala tuman, Yettitom shaharchasi, Nurafshon koʻchasi, 51-uy'),
  J('jin-mirishkor-tuman', 'kashkadarya',
    'Миришкор туман суди',
    'Mirishkor tuman, Yangi Mirishkor mahallasi, Mustaqillik koʻchasi, 14-uy'),
  J('jin-muborak-tuman', 'kashkadarya',
    'Муборак туман суди',
    'Muborak tuman, Zanjirsaroy shoh koʻchasi, 2/1-uy'),
  J('jin-nishon-tuman', 'kashkadarya',
    'Нишон туман суди',
    'Nishon tuman, Yangi Nishon shahri, Oʻzbekiston koʻchasi, 22-uy'),
  J('jin-qamashi-tuman', 'kashkadarya',
    'Қамаши туман суди',
    'Qamashi tuman, Istiqlol koʻchasi, 47-uy'),
  J('jin-yakkabog-tuman', 'kashkadarya',
    'Яккабоғ туман суди',
    'Yakkabogʻ tuman, Sahovat koʻchasi, 1-uy'),

  // ===== Karakalpakstan =====
  J('jin-kk-rsudi', 'karakalpakstan',
    'Қорақалпоғистон Республикаси суди',
    'Nukus shahar, «Doʻstlik guzari» MFY, I.Karimov koʻchasi, 122-uy'),
  J('jin-amudaryo-tuman', 'karakalpakstan',
    'Амударё туман суди',
    'Amudaryo tumani, Mangʻit shahar, «Doʻstlik» MFY, Gurlan koʻchasi'),
  J('jin-beruniy-tuman', 'karakalpakstan',
    'Беруний туман суди',
    'Beruniy tuman, Beruniy shahri, Kat koʻchasi, raqamsiz uy'),
  J('jin-bozatov-tuman', 'karakalpakstan',
    'Бўзатов туман суди',
    'Boʻzatov tumani, A.Temur koʻchasi, 6-uy'),
  J('jin-chimboy-tuman', 'karakalpakstan',
    'Чимбой туман суди',
    'Chimboy tumani, Doʻstlik guzari koʻchasi, raqamsiz uy'),
  J('jin-ellikqala-tuman', 'karakalpakstan',
    'Элликқалъа туман суди',
    'Ellikqalʼa tuman, Boʻston shahri, Al-Beruniy koʻchasi, 10-uy'),
  J('jin-kegeyli-tuman', 'karakalpakstan',
    'Кегейли туман суди',
    'Kegeyli tuman, Dustlik koʻchasi, raqamsiz uy'),
  J('jin-mojnoq-tuman', 'karakalpakstan',
    'Мўйноқ туман суди',
    'Muynoq tuman, Ajiniyaz koʻchasi, 72-uy'),
  J('jin-nukus-shahar', 'karakalpakstan',
    'Нукус шаҳар суди',
    'Nukus shahar, E.Olakuz koʻchasi, 173/1-uy'),
  J('jin-nukus-tuman', 'karakalpakstan',
    'Нукус туман суди',
    'Nukus tuman, Darsan koʻchasi, 25-uy'),
  J('jin-qonlikol-tuman', 'karakalpakstan',
    'Қонликўл туман суди',
    'Qonlikul tuman, Gʻarezsizlik koʻchasi, raqamsiz uy'),
  J('jin-qongirot-tuman', 'karakalpakstan',
    'Қўнғирот туман суди',
    'Qungirot tuman, Uzbekiston koʻchasi, 77 "A" uy'),
  J('jin-qorauzak-tuman', 'karakalpakstan',
    'Қораўзак туман суди',
    'Qorauzak tuman, Gʻarezsizlik koʻchasi, raqamsiz uy'),
  J('jin-shumanay-tuman', 'karakalpakstan',
    'Шуманай туман суди',
    'Shumanay tuman, Xalqlar dustligi koʻchasi, raqamsiz uy'),
  J('jin-taxiatosh-tuman', 'karakalpakstan',
    'Тахиатош туман суди',
    'Taxiatosh tumani, Sh.Rashidov koʻchasi, 16-uy'),
  J('jin-taxtakopir-tuman', 'karakalpakstan',
    'Тахтакўпир туман суди',
    'Taxtakupir tuman, Dustlik shox koʻchasi, raqamsiz uy'),
  J('jin-turtkul-tuman', 'karakalpakstan',
    'Тўрткўл туман суди',
    'Turtkul tuman, Turtkul koʻchasi, 62-uy'),
  J('jin-xojayli-tuman', 'karakalpakstan',
    'Хўжайли туман суди',
    'Xujayli tuman, Dustlik koʻchasi, raqamsiz uy'),

  // ===== Navoi =====
  J('jin-navoi-vsudi', 'navoi',
    'Навоий вилояти суди',
    'Navoiy shahar, Oʻzbekiston koʻchasi, 11A-uy'),
  J('jin-navoi-shahar', 'navoi',
    'Навоий шаҳар суди',
    'Navoiy shahar, Oʻzbekiston koʻchasi, 14-uy'),
  J('jin-karmana-tuman', 'navoi',
    'Кармана туман суди',
    'Karmana tuman, Temur malik koʻchasi, 16-uy'),
  J('jin-konimex-tuman', 'navoi',
    'Конимех туман суди',
    'Konimex tuman, Bunyodkor koʻchasi, 19-uy'),
  J('jin-navbahor-tuman', 'navoi',
    'Навбаҳор туман суди',
    'Navbahor tuman, Boburshox koʻchasi, 4-uy'),
  J('jin-nurota-tuman', 'navoi',
    'Нурота туман суди',
    'Nurota tuman, X.Xudoyqulov koʻchasi, 49-uy'),
  J('jin-qiziltepa-tuman', 'navoi',
    'Қизилтепа туман суди',
    'Qiziltepa tuman, Oʻzbekiston koʻchasi, 19-uy'),
  J('jin-tomdi-tuman', 'navoi',
    'Томди туман суди',
    'Tomdi tuman, Bazar Jirau koʻchasi, 4-uy'),
  J('jin-uchquduq-tuman', 'navoi',
    'Учқудуқ туман суди',
    'Uchquduq tuman, Navruz koʻchasi, 30-uy'),
  J('jin-xatirchi-tuman', 'navoi',
    'Хатирчи туман суди',
    'Xatirchi tuman, Pulkan koʻchasi, 60-uy'),
  J('jin-zarafshon-shahar', 'navoi',
    'Зарафшон шаҳар суди',
    'Zarafshon shahar, Marvarid koʻchasi, 1-uy'),

  // ===== Namangan =====
  J('jin-namangan-vsudi', 'namangan',
    'Наманган вилояти суди',
    'Namangan shahri, N.Namangoniy koʻchasi, 10-uy'),
  J('jin-namangan-shahar', 'namangan',
    'Наманган шаҳар суди',
    'Namangan shahar, N.Nomongoniy koʻchasi, 10-uy'),
  J('jin-namangan-tuman', 'namangan',
    'Наманган туман суди',
    'Namangan tumani, Toshbuloq shaharchasi, N.Oxunov koʻchasi, 3-uy'),
  J('jin-chortoq-tuman', 'namangan',
    'Чортоқ туман суди',
    'Chortoq tumani, Mustaqillik shox kochasi, 4-uy'),
  J('jin-chust-tuman', 'namangan',
    'Чуст туман суди',
    'Chust shahar, Karamsada MFY, Charagʻon koʻchasi, 74-uy'),
  J('jin-kosonsoy-tuman', 'namangan',
    'Косонсой туман суди',
    'Kosonsoy shahar, Gulobod koʻchasi, 11-uy'),
  J('jin-mingbuloq-tuman', 'namangan',
    'Мингбулоқ туман суди',
    'Mingbuloq tumani, Jomashoʻy shaharchasi, Ozodlik koʻchasi'),
  J('jin-norin-tuman', 'namangan',
    'Норин туман суди',
    'Norin tumani, Xaqulobod shahri, Beruniy koʻchasi, 21-uy'),
  J('jin-pop-tuman', 'namangan',
    'Поп туман суди',
    'Pop shahar, E.Yondosh koʻchasi, 7-uy'),
  J('jin-toraqorgon-tuman', 'namangan',
    'Тўрақўрғон туман суди',
    'Toʻraqoʻrgʻon shahri, Al-Fargʻoniy koʻchasi, 2-uy'),
  J('jin-uchqorgon-tuman', 'namangan',
    'Учқўрғон туман суди',
    'Uchqoʻrgʻon tumani, Lutfiy koʻchasi, 2-uy'),
  J('jin-uychi-tuman', 'namangan',
    'Уйчи туман суди',
    'Uychi tumani, Uychi shaharchasi, Beruniy koʻchasi'),
  J('jin-yangiqorgon-tuman', 'namangan',
    'Янгиқўрғон туман суди',
    'Yangiqoʻrgʻon tumani'),

  // ===== Samarkand =====
  J('jin-samarkand-vsudi', 'samarkand',
    'Самарқанд вилояти суди',
    'Samarqand shahar, Mingtut koʻchasi, 1-uy'),
  J('jin-samarkand-shahar', 'samarkand',
    'Самарқанд шаҳар суди',
    'Samarqand shahri, Bernuiy koʻchasi, 65-uy'),
  J('jin-samarkand-tuman', 'samarkand',
    'Самарқанд туман суди',
    'Samarqand tuman, Xoʻja Axror Vali-1 mahallasi'),
  J('jin-bulungur-tuman', 'samarkand',
    'Булунғур туман суди',
    'Bulungʻur tumani, Doʻslik koʻchasi, 24-uy'),
  J('jin-ishtixon-tuman', 'samarkand',
    'Иштихон туман суди',
    'Ishtixon shahri, Ishtixon koʻchasi, 11-uy'),
  J('jin-jomboy-tuman', 'samarkand',
    'Жомбой туман суди',
    'Jomboy shahri, Galakapa koʻchasi, 15-uy'),
  J('jin-kattaqorgon-shahar', 'samarkand',
    'Каттақўрғон шаҳар суди',
    'Kattaqoʻrgʻon shahar, A.Navoiy koʻchasi, 105-uy'),
  J('jin-kattaqorgon-tuman', 'samarkand',
    'Каттақўрғон туман суди',
    'Kattaqoʻrgʻon tumani, Mustaqillik koʻchasi, 37-uy'),
  J('jin-narpay-tuman', 'samarkand',
    'Нарпай туман суди',
    'Narpay tuman, Oqtosh shahri, I.Buxoriy koʻchasi, 5-uy'),
  J('jin-nurobod-tuman', 'samarkand',
    'Нуробод туман суди',
    'Nurobod shahri, Amir Temur koʻchasi, 14-uy'),
  J('jin-oqdaryo-tuman', 'samarkand',
    'Оқдарё туман суди',
    'Loyish shaharchasi, A.Temur koʻchasi, 17-uy'),
  J('jin-pastdargom-tuman', 'samarkand',
    'Пастдарғом туман суди',
    'Pastdargʻom tumani, Juma shahri, A.Temur koʻchasi'),
  J('jin-paxtachi-tuman', 'samarkand',
    'Пахтачи туман суди',
    'Paxtachi tuman, Ziyovuddin shaharchasi, Mustaqillik koʻchasi, 48-uy'),
  J('jin-payariq-tuman', 'samarkand',
    'Пайариқ туман суди',
    'Payariq tuman, Chelak shahri, Istiqlol koʻchasi, 59-uy'),
  J('jin-qoshrabod-tuman', 'samarkand',
    'Қўшрабод туман суди',
    'Qoʻshrobod tumani, Gʻofur Gʻulom koʻchasi, 1-uy'),
  J('jin-tayloq-tuman', 'samarkand',
    'Тойлоқ туман суди',
    'Tayloq tumani, Mustaqillik koʻchasi, 8-uy'),
  J('jin-urgut-tuman', 'samarkand',
    'Ургут туман суди',
    'Urgut tuman, Urgut shahri, Qoratepa koʻchasi'),

  // ===== Syrdarya =====
  J('jin-syrdarya-vsudi', 'syrdarya',
    'Сирдарё вилояти суди',
    'Guliston shahar, Navoiy shox koʻchasi, 47-uy'),
  J('jin-guliston-shahar', 'syrdarya',
    'Гулистон шаҳар суди',
    'Guliston shahar, Birlashgan koʻchasi, 9-uy'),
  J('jin-guliston-tuman', 'syrdarya',
    'Гулистон туман суди',
    'Guliston tumani, Dehqonobod shaharchasi, Turkiston koʻchasi, 26-uy'),
  J('jin-boyovut-tuman', 'syrdarya',
    'Боёвут туман суди',
    'Boyovut tumani, Boyovut shaharchasi, Tinchlik koʻchasi, 26-uy'),
  J('jin-hovos-tuman', 'syrdarya',
    'Ховос туман суди',
    'Hovos tumani, Bunyodkor mahallasi, Samarqand koʻchasi'),
  J('jin-mirzaobod-tuman', 'syrdarya',
    'Мирзаобод туман суди',
    'Mirzaobod tumani, Navroʻz shaharchasi, Mustaqillik koʻchasi, 5-uy'),
  J('jin-oqoltin-tuman', 'syrdarya',
    'Оқолтин туман суди',
    'Oqoltin tumani, Sardoba shaharchasi, Islomobod koʻchasi, 7-uy'),
  J('jin-sardoba-tuman', 'syrdarya',
    'Сардоба туман суди',
    'Sardoba tumani, Paxtaobod shaharchasi, Oyqor koʻchasi, 9-uy'),
  J('jin-sayhunobod-tuman', 'syrdarya',
    'Сайхунобод туман суди',
    'Sayhunobod tumani, Sayhun shaharchasi, Navoiy koʻchasi, 10-uy'),
  J('jin-shirin-shahar', 'syrdarya',
    'Ширин шаҳар суди',
    'Shirin shahri, A.Temur koʻchasi, 12-uy'),
  J('jin-syrdarya-tuman', 'syrdarya',
    'Сирдарё туман суди',
    'Sirdaryo tumani, Sirdaryo shahri, Oʻzbekiston koʻchasi, 80-uy'),
  J('jin-yangier-shahar', 'syrdarya',
    'Янгиер шаҳар суди',
    'Yangier shahri, Quruvchilar koʻchasi, 9-uy'),

  // ===== Surkhandarya =====
  J('jin-surkhandarya-vsudi', 'surkhandarya',
    'Сурхондарё вилояти суди',
    'Termiz shahri, Islom Karimov koʻchasi, 40-uy'),
  J('jin-termiz-shahar', 'surkhandarya',
    'Термиз шаҳар суди',
    'Termiz shahar, Iso At-Termiziy koʻchasi, 5A-uy'),
  J('jin-termiz-tuman', 'surkhandarya',
    'Термиз туман суди',
    'Termiz tumani, At-Termiziy koʻchasi, 3-uy'),
  J('jin-angor-tuman', 'surkhandarya',
    'Ангор туман суди',
    'Angor tumani, At-Termiziy koʻchasi, 1-uy'),
  J('jin-bandixon-tuman', 'surkhandarya',
    'Бандихон туман суди',
    'Bandixon tumani, Bandixon mahallasi, Guliston koʻchasi, 4-uy'),
  J('jin-boysun-tuman', 'surkhandarya',
    'Бойсун туман суди',
    'Boysun tumani, Olmazor koʻchasi'),
  J('jin-denov-tuman', 'surkhandarya',
    'Денов туман суди',
    'Denov tuman, Qoʻzichoqli mahallasi, Eski bog koʻchasi, 111-uy'),
  J('jin-jarqorgon-tuman', 'surkhandarya',
    'Жарқўрғон туман суди',
    'Jarqoʻrgʻon tumani, Y.Ohunboboyev koʻchasi, 1-uy'),
  J('jin-muzrabot-tuman', 'surkhandarya',
    'Музработ туман суди',
    'Muzrabot tumani, Quyoshkent koʻchasi, 2-uy'),
  J('jin-oltinsoy-tuman', 'surkhandarya',
    'Олтинсой туман суди',
    'Oltinsoy tumani, Boʻston maxallasi'),
  J('jin-qiziriq-tuman', 'surkhandarya',
    'Қизириқ туман суди',
    'Qiziriq tumani, Ibn Sino koʻchasi, 3-uy'),
  J('jin-qumqorgon-tuman', 'surkhandarya',
    'Қумқўрғон туман суди',
    'Qumqoʻrgʻon tumani, Oʻzbekiston koʻchasi, 22-uy'),
  J('jin-sariosiyo-tuman', 'surkhandarya',
    'Сариосиё туман суди',
    'Sariosiyo tumani, Mehr-shavqat koʻchasi'),
  J('jin-sherobod-tuman', 'surkhandarya',
    'Шеробод туман суди',
    'Sherobod tumani, Mustaqillik koʻchasi, 14-uy'),
  J('jin-shorchi-tuman', 'surkhandarya',
    'Шўрчи туман суди',
    'Shoʻrchi tuman, Mustaqillik koʻchasi, 115-uy'),
  J('jin-uzun-tuman', 'surkhandarya',
    'Узун туман суди',
    'Uzun tumani, Yangiroʻzgʻor mahallasi'),

  // ===== Tashkent region =====
  J('jin-tashreg-vsudi', 'tashkent_region',
    'Тошкент вилояти суди',
    'Toshkent shahar, Yakkasaroy tumani, Sh.Rustaveli koʻchasi, 93-uy'),
  J('jin-angren-shahar', 'tashkent_region',
    'Ангрен шаҳар суди',
    'Toshkent viloyati, Angren shahar, Bunyodkor koʻchasi, 1-uy'),
  J('jin-bekobod-shahar', 'tashkent_region',
    'Бекобод шаҳар суди',
    'Toshkent viloyati, Bekobod shahar, Istiqlol koʻchasi, 15-uy'),
  J('jin-bekobod-tuman', 'tashkent_region',
    'Бекобод туман суди',
    'Toshkent viloyati, Bekobod tumani, Zafar shaharchasi, Mustaqillik koʻchasi, 13-uy'),
  J('jin-boka-tuman', 'tashkent_region',
    'Бўка туман суди',
    'Toshkent viloyati, Boʻka tumani, Moxira Maxmudova koʻchasi, 1-uy'),
  J('jin-bostonliq-tuman', 'tashkent_region',
    'Бўстонлиқ туман суди',
    'Toshkent viloyati, Boʻstonliq tumani, Fazalkent shaharchasi, Lutfiy koʻchasi, 1-uy'),
  J('jin-chinoz-tuman', 'tashkent_region',
    'Чиноз туман суди',
    'Toshkent viloyati, Chinoz tumani, Samarqand koʻchasi, 3-uy'),
  J('jin-chirchiq-shahar', 'tashkent_region',
    'Чирчиқ шаҳар суди',
    'Toshkent viloyati, Chirchiq shahar, A.Navoiy koʻchasi, 139-uy'),
  J('jin-nurafshon-shahar', 'tashkent_region',
    'Нурафшон шаҳар суди',
    'Toshkent viloyati, Nurafshon shahar, Toshkent-yoʻli koʻchasi, 240-uy'),
  J('jin-ohangaron-shahar', 'tashkent_region',
    'Оҳангарон шаҳар суди',
    'Toshkent viloyati, Ohangaron shahar, Ezgulik koʻchasi, 100-uy'),
  J('jin-ohangaron-tuman', 'tashkent_region',
    'Оҳангарон туман суди',
    'Toshkent viloyati, Ohangaron shahar, Ezgulik koʻchasi, 100-uy'),
  J('jin-olmaliq-shahar', 'tashkent_region',
    'Олмалиқ шаҳар суди',
    'Toshkent viloyati, Olmaliq shahar, Ramazonov koʻchasi, 14A-uy'),
  J('jin-ortachirchiq-tuman', 'tashkent_region',
    'Ўрта Чирчиқ туман суди',
    'Toshkent viloyati, Nurafshon shahar, Toshkent-yoʻli koʻchasi, 240-uy'),
  J('jin-oqqorgon-tuman', 'tashkent_region',
    'Оққўрғон туман суди',
    'Toshkent viloyati, Oqqoʻrgʻon tumani, Furqat koʻchasi, 1-uy'),
  J('jin-parkent-tuman', 'tashkent_region',
    'Паркент туман суди',
    'Toshkent viloyati, Parkent tumani, Kumushkon koʻchasi, 5-uy'),
  J('jin-piskent-tuman', 'tashkent_region',
    'Пискент туман суди',
    'Toshkent viloyati, Pskent tumani, M.Malikov koʻchasi, 1-uy'),
  J('jin-qibray-tuman', 'tashkent_region',
    'Қибрай туман суди',
    'Toshkent viloyati, Qibray tumani, Zebiniso koʻchasi, 10-uy'),
  J('jin-quyichirchiq-tuman', 'tashkent_region',
    'Қуйи Чирчиқ туман суди',
    'Toshkent viloyati, Quyichirchiq tumani, Oqqoʻrgʻon koʻchasi, 1-uy'),
  J('jin-tashreg-tuman', 'tashkent_region',
    'Тошкент туман суди',
    'Toshkent viloyati, Toshkent tumani, Keles shahri, Keles-yoʻli koʻchasi, 2-uy'),
  J('jin-yangiyul-shahar', 'tashkent_region',
    'Янгийўл шаҳар суди',
    'Toshkent viloyati, Yangyoʻl shahar, Ibn-Sino koʻchasi, 20-uy'),
  J('jin-yangiyul-tuman', 'tashkent_region',
    'Янгийўл туман суди',
    'Toshkent viloyati, Yangyoʻl shahar, Ibn-Sino koʻchasi, 20-uy'),
  J('jin-yuqorichirchiq-tuman', 'tashkent_region',
    'Юқори Чирчиқ туман суди',
    'Toshkent viloyati, Yuqorichirchiq tumani, Yangibozor qoʻrgʻoni, Mustaqillik koʻchasi, 77-uy'),
  J('jin-zangiota-tuman', 'tashkent_region',
    'Зангиота туман суди',
    'Toshkent viloyati, Zangiota tumani, Eshonguzar qoʻrgʻoni, Mustaqillik koʻchasi, 20-uy'),

  // ===== Tashkent city =====
  J('jin-tashcity-shahar', 'tashkent_city',
    'Тошкент шаҳар суди',
    'Toshkent shahri, Alisher Navoiy koʻchasi, 23-uy'),
  J('jin-tashcity-bektemir', 'tashkent_city',
    'Бектемир туман суди',
    'Toshkent shahar, Bektemir tumani, X.Boyqaro koʻchasi, 9a-uy'),
  J('jin-tashcity-chilonzor', 'tashkent_city',
    'Чилонзор туман суди',
    'Toshkent shahar, Sharq tongi koʻchasi, 1-a'),
  J('jin-tashcity-mirobod', 'tashkent_city',
    'Миробод туман суди',
    'Toshkent shahar, Mirobod tumani, Fidokor koʻchasi, 38-uy'),
  J('jin-tashcity-mirzo-ulugbek', 'tashkent_city',
    'Мирзо Улуғбек туман суди',
    'Toshkent shahar, Sayram 7-tor koʻchasi, 2-uy'),
  J('jin-tashcity-olmazor', 'tashkent_city',
    'Олмазор туман суди',
    'Toshkent shahar, Kichik halqa yoʻli koʻchasi, 9-uy'),
  J('jin-tashcity-sergeli', 'tashkent_city',
    'Сергели туман суди',
    'Toshkent shahar, Sirgʻali tumani, Yangi Sirgʻali koʻchasi'),
  J('jin-tashcity-shayxontohur', 'tashkent_city',
    'Шайхантохур туман суди',
    'Toshkent shahar, Shayxontohur tumani, Beruniy koʻchasi, 3/4-uy'),
  J('jin-tashcity-uchtepa', 'tashkent_city',
    'Учтепа туман суди',
    'Toshkent shahar, Foziltepa koʻchasi, 42a-uy'),
  J('jin-tashcity-yakkasaroy', 'tashkent_city',
    'Яккасарой туман суди',
    'Toshkent shahar, Shota Rustavelli koʻchasi, 62-uy'),
  J('jin-tashcity-yashnobod', 'tashkent_city',
    'Яшнобод туман суди',
    'Toshkent shahar, Yashnobod tumani, Taraqqiyot 1-berk koʻchasi, 8-uy'),
  J('jin-tashcity-yangihayot', 'tashkent_city',
    'Янгиҳаёт туман суди',
    'Toshkent shahar, Yangihayot tumani, Lutfikor koʻchasi, 33-uy'),
  J('jin-tashcity-yunusobod', 'tashkent_city',
    'Юнусобод туман суди',
    'Toshkent shahar, A.Temur koʻchasi, 133-uy'),

  // ===== Fergana =====
  J('jin-fergana-vsudi', 'fergana',
    'Фарғона вилояти суди',
    'Fargʻona shahar, Sohibqiron Temur koʻchasi, 30-uy'),
  J('jin-fergana-shahar', 'fergana',
    'Фарғона шаҳар суди',
    'Fargʻona shahar, Yuksalish koʻchasi, 103-uy'),
  J('jin-fergana-tuman', 'fergana',
    'Фарғона туман суди',
    'Fargʻona tumani, Vodil shaharchasi, Buloqboshi koʻchasi, raqamsiz uy'),
  J('jin-bogdod-tuman', 'fergana',
    'Боғдод туман суди',
    'Bogʻdod tumani, Orzu koʻchasi'),
  J('jin-besharik-tuman', 'fergana',
    'Бешариқ туман суди',
    'Beshariq tumani, Oltin Vodiy koʻchasi, 101-uy'),
  J('jin-buvayda-tuman', 'fergana',
    'Бувайда туман суди',
    'Buvayda tumani, Yangiqoʻrgʻon shaharchasi, Bogʻieram koʻchasi, 56-uy'),
  J('jin-dangara-tuman', 'fergana',
    'Данғара туман суди',
    'Dangʻara tumani, Muqumiy koʻchasi, 2-uy'),
  J('jin-furqat-tuman', 'fergana',
    'Фурқат туман суди',
    'Furqat tumani, Ardaxshon qishlogʻi, Tayanch koʻchasi, 5-uy'),
  J('jin-margilon-shahar', 'fergana',
    'Марғилон шаҳар суди',
    'Margʻilon shahar, Nurafshon koʻchasi, 9-uy'),
  J('jin-oltiariq-tuman', 'fergana',
    'Олтиариқ туман суди',
    'Oltiariq tumani, Oltiariq shaharchasi, Oʻzbekiston koʻchasi, 28-uy'),
  J('jin-ozbekiston-tuman', 'fergana',
    'Ўзбекистон туман суди',
    'Oʻzbekiston tumani, Konizar qishlogʻi, A.Navoiy koʻchasi, 18-uy'),
  J('jin-qoqon-shahar', 'fergana',
    'Қўқон шаҳар суди',
    'Qoʻqon shahar, I.Buhoriy koʻchasi, 37-uy'),
  J('jin-quva-tuman', 'fergana',
    'Қува туман суди',
    'Quva tumani, Qayqubbot koʻchasi, 184-uy'),
  J('jin-quvasoy-shahar', 'fergana',
    'Қувасой шаҳар суди',
    'Quvasoy shahar, Mustaqillik koʻchasi, 95-uy'),
  J('jin-qoshtepa-tuman', 'fergana',
    'Қўштепа туман суди',
    'Qoʻshtepa tumani, Mirobod koʻchasi'),
  J('jin-rishton-tuman', 'fergana',
    'Риштон туман суди',
    'Rishton tumani, Markaz MFY, Roshidoniya koʻchasi, 187A-uy'),
  J('jin-sox-tuman', 'fergana',
    'Сўх туман суди',
    'Soʻx tumani, Rovon shaharchasi, A.Temur koʻchasi, 187-uy'),
  J('jin-toshloq-tuman', 'fergana',
    'Тошлоқ туман суди',
    'Toshloq tumani, Dovon koʻchasi, 93-uy'),
  J('jin-uchkoprik-tuman', 'fergana',
    'Учкўприк туман суди',
    'Uchkoʻprik tumani, X.Olimjon koʻchasi, 80-uy'),
  J('jin-yozyovon-tuman', 'fergana',
    'Ёзёвон туман суди',
    'Yozyovon tumani, Yozyovon shaharchasi, Xidoyat koʻchasi, 3-uy'),

  // ===== Khorezm =====
  J('jin-khorezm-vsudi', 'khorezm',
    'Хоразм вилояти суди',
    'Urganch shahri, Tinchlik koʻchasi, 22-uy'),
  J('jin-urganch-shahar', 'khorezm',
    'Урганч шаҳар суди',
    'Urganch shaxri, Sheroziy koʻchasi, 14-uy'),
  J('jin-urganch-tuman', 'khorezm',
    'Урганч туман суди',
    'Urganch tumani, Mustaqillik koʻchasi, 12/1-uy'),
  J('jin-bogot-tuman', 'khorezm',
    'Боғот туман суди',
    'Bogʻot tumani, Baynalmilalchi koʻchasi, 1-uy'),
  J('jin-gurlan-tuman', 'khorezm',
    'Гурлан туман суди',
    'Gurlan tumani, P.Maxmud koʻchasi, 26-uy'),
  J('jin-khazorasp-tuman', 'khorezm',
    'Хазорасп туман суди',
    'Xazorasp tumani, Mustaqillik koʻchasi, 44-uy'),
  J('jin-khiva-shahar', 'khorezm',
    'Хива шаҳар суди',
    'Xiva shahar, A.Temur koʻchasi, 3-uy'),
  J('jin-khiva-tuman', 'khorezm',
    'Хива туман суди',
    'Xiva tumani, A.Temur koʻchasi, 3-uy'),
  J('jin-khonqa-tuman', 'khorezm',
    'Хонқа туман суди',
    'Xonqa tumani, M.Abdullaev koʻchasi, 2-uy'),
  J('jin-qoshkopir-tuman', 'khorezm',
    'Қўшкўпир туман суди',
    'Qoʻshkopir tumani, Mustaqillik koʻchasi, raqamsiz uy'),
  J('jin-shovot-tuman', 'khorezm',
    'Шовот туман суди',
    'Shovot tumani, Turkiston koʻchasi, 77-uy'),
  J('jin-tuproqqala-tuman', 'khorezm',
    'Тупроққалъа туман суди',
    'Pitnak shahar, Mustaqillik koʻchasi, 1-uy'),
  J('jin-yangiariq-tuman', 'khorezm',
    'Янгиариқ туман суди',
    'Yangiariq tumani, Urganch koʻchasi, 2-uy'),
  J('jin-yangibozor-tuman', 'khorezm',
    'Янгибозор туман суди',
    'Yangibozor tumani, J.Manguberdi koʻchasi, 46-uy'),
];

/**
 * Set of (courtType, region) pairs that have authoritative MySud data
 * below. For those pairs we use the explicit entries; for pairs NOT
 * in this set we fall back to mirrorFuqarolikFor() so every region/type
 * combination still shows a populated picker. As real MySud data lands
 * for jinoyat / iqtisodiy / etc., move them out of the mirror fallback
 * by adding to REAL_NON_FUQAROLIK_COURTS — the dedupe logic does the
 * rest automatically.
 */
const REAL_NON_FUQAROLIK_COURTS: DistrictCourtDef[] = [
  ...MAMURIY_COURTS,
  ...IQTISODIY_COURTS,
  ...JINOYAT_COURTS,
];

/**
 * Final exported list shown to users. Order:
 *   1. fuqarolik (authoritative)
 *   2. real MySud entries for jin / mam / iqt
 *   3. mirror-fallback for any (type, region) pairs without real data
 */
const REAL_KEYS = new Set(
  REAL_NON_FUQAROLIK_COURTS.map((c) => `${c.courtTypeCode}:${c.regionCode}`),
);
const NON_FUQAROLIK_TYPES = ['jinoyat', 'mamuriy', 'iqtisodiy'] as const;
const MIRRORED_COURTS: DistrictCourtDef[] = FUQAROLIK_COURTS.flatMap((c) =>
  NON_FUQAROLIK_TYPES.filter((t) => !REAL_KEYS.has(`${t}:${c.regionCode}`)).map(
    (t) => mirrorFuqarolikFor(c, t),
  ),
);

export const DISTRICT_COURTS: DistrictCourtDef[] = [
  ...FUQAROLIK_COURTS,
  ...REAL_NON_FUQAROLIK_COURTS,
  ...MIRRORED_COURTS,
];

export function getDistrictCourtByCode(code: string): DistrictCourtDef | undefined {
  return DISTRICT_COURTS.find((d) => d.code === code);
}

/** All district courts for a (courtType, region) pair, in declared order. */
export function getDistrictCourtsFor(
  courtTypeCode: string,
  regionCode: string,
): DistrictCourtDef[] {
  return DISTRICT_COURTS.filter(
    (d) => d.courtTypeCode === courtTypeCode && d.regionCode === regionCode,
  );
}
