import type { Locale } from '../i18n';

/**
 * District / interdistrict court within a region. After the user picks
 * one, its `name` is stored in `state.values.court_name` and rendered
 * into the document header.
 *
 * Currently only `courtTypeCode: 'fuqarolik'` is populated. The data
 * was derived from the user-supplied screenshots of the Iqtisodiy
 * court list; per their decision the "iqtisodiy" word is replaced by
 * "fuqarolik" in court names. Some real Fuqarolik courts may differ —
 * the list is a starting point and should be revised when authoritative
 * Fuqarolik data is available.
 */
export interface DistrictCourtDef {
  code: string;
  regionCode: string;
  courtTypeCode: string;
  /** Full court name used both for the button label AND written into
   *  the document as `court_name`. */
  name: Record<Locale, string>;
}

function L(cy: string, la: string, ru: string): Record<Locale, string> {
  return { uz_cyrillic: cy, uz_latin: la, ru };
}

function D(
  code: string,
  regionCode: string,
  cy: string,
  la: string,
  ru: string,
): DistrictCourtDef {
  return {
    code,
    regionCode,
    courtTypeCode: 'fuqarolik',
    name: L(cy, la, ru),
  };
}

export const DISTRICT_COURTS: DistrictCourtDef[] = [
  // ===== Андижон вилояти =====
  D('fuq-andijan-vsudi', 'andijan',
    'Андижон вилоят суди',
    'Andijon viloyat sudi',
    'Андижанский областной суд'),
  D('fuq-andijan-tlf', 'andijan',
    'Андижон туманлараро фуқаролик суди',
    'Andijon tumanlararo fuqarolik sudi',
    'Андижанский межрайонный гражданский суд'),
  D('fuq-asaka-tlf', 'andijan',
    'Асака туманлараро фуқаролик суди',
    'Asaka tumanlararo fuqarolik sudi',
    'Асакинский межрайонный гражданский суд'),
  D('fuq-boston-tlf', 'andijan',
    'Бўстон туманлараро фуқаролик суди',
    'Boʻston tumanlararo fuqarolik sudi',
    'Бустанский межрайонный гражданский суд'),
  D('fuq-izboskan-tlf', 'andijan',
    'Избоскан туманлараро фуқаролик суди',
    'Izboskan tumanlararo fuqarolik sudi',
    'Избосканский межрайонный гражданский суд'),
  D('fuq-qorgontepa-tlf', 'andijan',
    'Қўрғонтепа туманлараро фуқаролик суди',
    'Qoʻrgʻontepa tumanlararo fuqarolik sudi',
    'Кургантепинский межрайонный гражданский суд'),
  D('fuq-xojaobod-tlf', 'andijan',
    'Хўжаобод туманлараро фуқаролик суди',
    'Xoʻjaobod tumanlararo fuqarolik sudi',
    'Ходжаабадский межрайонный гражданский суд'),

  // ===== Бухоро вилояти =====
  D('fuq-bukhara-vsudi', 'bukhara',
    'Бухоро вилоят суди',
    'Buxoro viloyat sudi',
    'Бухарский областной суд'),
  D('fuq-bukhara-tlf', 'bukhara',
    'Бухоро туманлараро фуқаролик суди',
    'Buxoro tumanlararo fuqarolik sudi',
    'Бухарский межрайонный гражданский суд'),
  D('fuq-gijduvon-tlf', 'bukhara',
    'Ғиждувон туманлараро фуқаролик суди',
    'Gʻijduvon tumanlararo fuqarolik sudi',
    'Гиждуванский межрайонный гражданский суд'),
  D('fuq-kogon-tlf', 'bukhara',
    'Когон туманлараро фуқаролик суди',
    'Kogon tumanlararo fuqarolik sudi',
    'Каганский межрайонный гражданский суд'),
  D('fuq-qorakul-tlf', 'bukhara',
    'Қоракўл туманлараро фуқаролик суди',
    'Qoraqoʻl tumanlararo fuqarolik sudi',
    'Каракульский межрайонный гражданский суд'),
  D('fuq-peshku-tlf', 'bukhara',
    'Пешку туманлараро фуқаролик суди',
    'Peshku tumanlararo fuqarolik sudi',
    'Пешкунский межрайонный гражданский суд'),
  D('fuq-romitan-tlf', 'bukhara',
    'Ромитан туманлараро фуқаролик суди',
    'Romitan tumanlararo fuqarolik sudi',
    'Ромитанский межрайонный гражданский суд'),

  // ===== Жиззах вилояти =====
  D('fuq-jizzakh-vsudi', 'jizzakh',
    'Жиззах вилоят суди',
    'Jizzax viloyat sudi',
    'Джизакский областной суд'),
  D('fuq-gallaorol-tlf', 'jizzakh',
    'Ғаллаорол туманлараро фуқаролик суди',
    'Gʻallaorol tumanlararo fuqarolik sudi',
    'Галляаральский межрайонный гражданский суд'),
  D('fuq-dustlik-tlf', 'jizzakh',
    'Дўстлик туманлараро фуқаролик суди',
    'Doʻstlik tumanlararo fuqarolik sudi',
    'Дустликский межрайонный гражданский суд'),
  D('fuq-jizzakh-tlf', 'jizzakh',
    'Жиззах туманлараро фуқаролик суди',
    'Jizzax tumanlararo fuqarolik sudi',
    'Джизакский межрайонный гражданский суд'),
  D('fuq-zomin-tlf', 'jizzakh',
    'Зомин туманлараро фуқаролик суди',
    'Zomin tumanlararo fuqarolik sudi',
    'Зааминский межрайонный гражданский суд'),
  D('fuq-forish-tf', 'jizzakh',
    'Фориш туман фуқаролик суди',
    'Forish tuman fuqarolik sudi',
    'Фаришский районный гражданский суд'),

  // ===== Қашқадарё вилояти =====
  D('fuq-qash-vsudi', 'kashkadarya',
    'Қашқадарё вилоят суди',
    'Qashqadaryo viloyat sudi',
    'Кашкадарьинский областной суд'),
  D('fuq-guzor-tlf', 'kashkadarya',
    'Ғузор туманлараро фуқаролик суди',
    'Gʻuzor tumanlararo fuqarolik sudi',
    'Гузарский межрайонный гражданский суд'),
  D('fuq-qarshi-tlf', 'kashkadarya',
    'Қарши туманлараро фуқаролик суди',
    'Qarshi tumanlararo fuqarolik sudi',
    'Каршинский межрайонный гражданский суд'),
  D('fuq-kasbi-tlf', 'kashkadarya',
    'Касби туманлараро фуқаролик суди',
    'Kasbi tumanlararo fuqarolik sudi',
    'Касбинский межрайонный гражданский суд'),
  D('fuq-koson-tlf', 'kashkadarya',
    'Косон туманлараро фуқаролик суди',
    'Koson tumanlararo fuqarolik sudi',
    'Касанский межрайонный гражданский суд'),
  D('fuq-chiroqchi-tlf', 'kashkadarya',
    'Чироқчи туманлараро фуқаролик суди',
    'Chiroqchi tumanlararo fuqarolik sudi',
    'Чиракчинский межрайонный гражданский суд'),
  D('fuq-shahrisabz-tlf', 'kashkadarya',
    'Шаҳрисабз туманлараро фуқаролик суди',
    'Shahrisabz tumanlararo fuqarolik sudi',
    'Шахрисабзский межрайонный гражданский суд'),
  D('fuq-yakkabog-tlf', 'kashkadarya',
    'Яккабоғ туманлараро фуқаролик суди',
    'Yakkabogʻ tumanlararo fuqarolik sudi',
    'Яккабагский межрайонный гражданский суд'),

  // ===== Қорақалпоғистон Республикаси =====
  D('fuq-kk-rsudi', 'karakalpakstan',
    'Қорақалпоғистон Республикаси суди',
    'Qoraqalpogʻiston Respublikasi sudi',
    'Верховный суд Республики Каракалпакстан'),
  D('fuq-amudaryo-tf', 'karakalpakstan',
    'Амударё туман фуқаролик суди',
    'Amudaryo tuman fuqarolik sudi',
    'Амударьинский районный гражданский суд'),
  D('fuq-beruniy-tlf', 'karakalpakstan',
    'Беруний туманлараро фуқаролик суди',
    'Beruniy tumanlararo fuqarolik sudi',
    'Берунийский межрайонный гражданский суд'),
  D('fuq-qongirot-tlf', 'karakalpakstan',
    'Қўнғирот туманлараро фуқаролик суди',
    'Qoʻngʻirot tumanlararo fuqarolik sudi',
    'Кунградский межрайонный гражданский суд'),
  D('fuq-nukus-tlf', 'karakalpakstan',
    'Нукус туманлараро фуқаролик суди',
    'Nukus tumanlararo fuqarolik sudi',
    'Нукусский межрайонный гражданский суд'),
  D('fuq-chimboy-tlf', 'karakalpakstan',
    'Чимбой туманлараро фуқаролик суди',
    'Chimboy tumanlararo fuqarolik sudi',
    'Чимбайский межрайонный гражданский суд'),

  // ===== Навоий вилояти =====
  D('fuq-navoi-vsudi', 'navoi',
    'Навоий вилоят суди',
    'Navoiy viloyat sudi',
    'Навоийский областной суд'),
  D('fuq-zarafshon-tlf', 'navoi',
    'Зарафшон туманлараро фуқаролик суди',
    'Zarafshon tumanlararo fuqarolik sudi',
    'Зарафшанский межрайонный гражданский суд'),
  D('fuq-karmana-tlf', 'navoi',
    'Кармана туманлараро фуқаролик суди',
    'Karmana tumanlararo fuqarolik sudi',
    'Карманинский межрайонный гражданский суд'),
  D('fuq-navbahor-tlf', 'navoi',
    'Навбаҳор туманлараро фуқаролик суди',
    'Navbahor tumanlararo fuqarolik sudi',
    'Навбахорский межрайонный гражданский суд'),
  D('fuq-uchquduq-tf', 'navoi',
    'Учқудуқ туман фуқаролик суди',
    'Uchquduq tuman fuqarolik sudi',
    'Учкудукский районный гражданский суд'),

  // ===== Наманган вилояти =====
  D('fuq-namangan-vsudi', 'namangan',
    'Наманган вилоят суди',
    'Namangan viloyat sudi',
    'Наманганский областной суд'),
  D('fuq-namangan-tlf', 'namangan',
    'Наманган туманлараро фуқаролик суди',
    'Namangan tumanlararo fuqarolik sudi',
    'Наманганский межрайонный гражданский суд'),
  D('fuq-uchqorgon-tlf', 'namangan',
    'Учқўрғон туманлараро фуқаролик суди',
    'Uchqoʻrgʻon tumanlararo fuqarolik sudi',
    'Учкурганский межрайонный гражданский суд'),
  D('fuq-chust-tlf', 'namangan',
    'Чуст туманлараро фуқаролик суди',
    'Chust tumanlararo fuqarolik sudi',
    'Чустский межрайонный гражданский суд'),
  D('fuq-yangiqorgon-tlf', 'namangan',
    'Янгиқўрғон туманлараро фуқаролик суди',
    'Yangiqoʻrgʻon tumanlararo fuqarolik sudi',
    'Янгикурганский межрайонный гражданский суд'),

  // ===== Самарқанд вилояти =====
  D('fuq-samarkand-vsudi', 'samarkand',
    'Самарқанд вилоят суди',
    'Samarqand viloyat sudi',
    'Самаркандский областной суд'),
  D('fuq-jomboy-tlf', 'samarkand',
    'Жомбой туманлараро фуқаролик суди',
    'Jomboy tumanlararo fuqarolik sudi',
    'Джамбайский межрайонный гражданский суд'),
  D('fuq-ishtixon-tlf', 'samarkand',
    'Иштихон туманлараро фуқаролик суди',
    'Ishtixon tumanlararo fuqarolik sudi',
    'Иштыханский межрайонный гражданский суд'),
  D('fuq-kattaqorgon-tlf', 'samarkand',
    'Каттақўрғон туманлараро фуқаролик суди',
    'Kattaqoʻrgʻon tumanlararo fuqarolik sudi',
    'Каттакурганский межрайонный гражданский суд'),
  D('fuq-nurobod-tf', 'samarkand',
    'Нуробод туман фуқаролик суди',
    'Nurobod tuman fuqarolik sudi',
    'Нурабадский районный гражданский суд'),
  D('fuq-payariq-tlf', 'samarkand',
    'Пайариқ туманлараро фуқаролик суди',
    'Payariq tumanlararo fuqarolik sudi',
    'Пайарыкский межрайонный гражданский суд'),
  D('fuq-pastdargom-tlf', 'samarkand',
    'Пастдарғом туманлараро фуқаролик суди',
    'Pastdargʻom tumanlararo fuqarolik sudi',
    'Пастдаргомский межрайонный гражданский суд'),
  D('fuq-samarkand-shahar', 'samarkand',
    'Самарқанд шаҳар фуқаролик суди',
    'Samarqand shahar fuqarolik sudi',
    'Самаркандский городской гражданский суд'),
  D('fuq-tayloq-tlf', 'samarkand',
    'Тайлоқ туманлараро фуқаролик суди',
    'Tayloq tumanlararo fuqarolik sudi',
    'Тайлакский межрайонный гражданский суд'),

  // ===== Сирдарё вилояти =====
  D('fuq-syrdarya-vsudi', 'syrdarya',
    'Сирдарё вилоят суди',
    'Sirdaryo viloyat sudi',
    'Сырдарьинский областной суд'),
  D('fuq-boyovut-tlf', 'syrdarya',
    'Боёвут туманлараро фуқаролик суди',
    'Boyovut tumanlararo fuqarolik sudi',
    'Баяутский межрайонный гражданский суд'),
  D('fuq-guliston-tlf', 'syrdarya',
    'Гулистон туманлараро фуқаролик суди',
    'Guliston tumanlararo fuqarolik sudi',
    'Гулистанский межрайонный гражданский суд'),
  D('fuq-oqoltin-tlf', 'syrdarya',
    'Оқолтин туманлараро фуқаролик суди',
    'Oqoltin tumanlararo fuqarolik sudi',
    'Акалтынский межрайонный гражданский суд'),
  D('fuq-syrdarya-tlf', 'syrdarya',
    'Сирдарё туманлараро фуқаролик суди',
    'Sirdaryo tumanlararo fuqarolik sudi',
    'Сырдарьинский межрайонный гражданский суд'),

  // ===== Сурхондарё вилояти =====
  D('fuq-surkhandarya-vsudi', 'surkhandarya',
    'Сурхондарё вилоят суди',
    'Surxondaryo viloyat sudi',
    'Сурхандарьинский областной суд'),
  D('fuq-boysun-tf', 'surkhandarya',
    'Бойсун туман фуқаролик суди',
    'Boysun tuman fuqarolik sudi',
    'Байсунский районный гражданский суд'),
  D('fuq-denov-tlf', 'surkhandarya',
    'Денов туманлараро фуқаролик суди',
    'Denov tumanlararo fuqarolik sudi',
    'Денауский межрайонный гражданский суд'),
  D('fuq-qumqorgon-tlf', 'surkhandarya',
    'Қумқўрғон туманлараро фуқаролик суди',
    'Qumqoʻrgʻon tumanlararo fuqarolik sudi',
    'Кумкурганский межрайонный гражданский суд'),
  D('fuq-sariosiyo-tlf', 'surkhandarya',
    'Сариосиё туманлараро фуқаролик суди',
    'Sariosiyo tumanlararo fuqarolik sudi',
    'Сариасийский межрайонный гражданский суд'),
  D('fuq-termiz-tlf', 'surkhandarya',
    'Термиз туманлараро фуқаролик суди',
    'Termiz tumanlararo fuqarolik sudi',
    'Термезский межрайонный гражданский суд'),
  D('fuq-sherobod-tlf', 'surkhandarya',
    'Шеробод туманлараро фуқаролик суди',
    'Sherobod tumanlararo fuqarolik sudi',
    'Шерабадский межрайонный гражданский суд'),

  // ===== Тошкент вилояти =====
  D('fuq-tashkentreg-vsudi', 'tashkent_region',
    'Тошкент вилоят суди',
    'Toshkent viloyat sudi',
    'Ташкентский областной суд'),
  D('fuq-bekobod-tlf', 'tashkent_region',
    'Бекобод туманлараро фуқаролик суди',
    'Bekobod tumanlararo fuqarolik sudi',
    'Бекабадский межрайонный гражданский суд'),
  D('fuq-zangiota-tlf', 'tashkent_region',
    'Зангиота туманлараро фуқаролик суди',
    'Zangiota tumanlararo fuqarolik sudi',
    'Зангиатинский межрайонный гражданский суд'),
  D('fuq-quyichirchiq-tlf', 'tashkent_region',
    'Қуйичирчиқ туманлараро фуқаролик суди',
    'Quyichirchiq tumanlararo fuqarolik sudi',
    'Куйичирчикский межрайонный гражданский суд'),
  D('fuq-ohangaron-tlf', 'tashkent_region',
    'Оҳангарон туманлараро фуқаролик суди',
    'Ohangaron tumanlararo fuqarolik sudi',
    'Ахангаранский межрайонный гражданский суд'),
  D('fuq-ortachirchiq-tlf', 'tashkent_region',
    'Ўртачирчиқ туманлараро фуқаролик суди',
    'Oʻrtachirchiq tumanlararo fuqarolik sudi',
    'Уртачирчикский межрайонный гражданский суд'),
  D('fuq-chirchiq-tlf', 'tashkent_region',
    'Чирчиқ туманлараро фуқаролик суди',
    'Chirchiq tumanlararo fuqarolik sudi',
    'Чирчикский межрайонный гражданский суд'),
  D('fuq-yuqorichirchiq-tlf', 'tashkent_region',
    'Юқоричирчиқ туманлараро фуқаролик суди',
    'Yuqorichirchiq tumanlararo fuqarolik sudi',
    'Юкоричирчикский межрайонный гражданский суд'),

  // ===== Тошкент шаҳар =====
  D('fuq-tashcity-shahar', 'tashkent_city',
    'Тошкент шаҳар суди',
    'Toshkent shahar sudi',
    'Ташкентский городской суд'),
  D('fuq-tashcity-tlf', 'tashkent_city',
    'Тошкент туманлараро фуқаролик суди',
    'Toshkent tumanlararo fuqarolik sudi',
    'Ташкентский межрайонный гражданский суд'),

  // ===== Фарғона вилояти =====
  D('fuq-fergana-vsudi', 'fergana',
    'Фарғона вилоят суди',
    'Fargʻona viloyat sudi',
    'Ферганский областной суд'),
  D('fuq-qoqon-tlf', 'fergana',
    'Қўқон туманлараро фуқаролик суди',
    'Qoʻqon tumanlararo fuqarolik sudi',
    'Кокандский межрайонный гражданский суд'),
  D('fuq-margilon-tlf', 'fergana',
    'Марғилон туманлараро фуқаролик суди',
    'Margʻilon tumanlararo fuqarolik sudi',
    'Маргиланский межрайонный гражданский суд'),
  D('fuq-rishton-tlf', 'fergana',
    'Риштон туманлараро фуқаролик суди',
    'Rishton tumanlararo fuqarolik sudi',
    'Риштанский межрайонный гражданский суд'),
  D('fuq-ozbekiston-tlf', 'fergana',
    'Ўзбекистон туманлараро фуқаролик суди',
    'Oʻzbekiston tumanlararo fuqarolik sudi',
    'Узбекистанский межрайонный гражданский суд'),
  D('fuq-fergana-tlf', 'fergana',
    'Фарғона туманлараро фуқаролик суди',
    'Fargʻona tumanlararo fuqarolik sudi',
    'Ферганский межрайонный гражданский суд'),

  // ===== Хоразм вилояти =====
  D('fuq-khorezm-vsudi', 'khorezm',
    'Хоразм вилоят суди',
    'Xorazm viloyat sudi',
    'Хорезмский областной суд'),
  D('fuq-bogot-tlf', 'khorezm',
    'Боғот туманлараро фуқаролик суди',
    'Bogʻot tumanlararo fuqarolik sudi',
    'Багатский межрайонный гражданский суд'),
  D('fuq-urganch-tlf', 'khorezm',
    'Урганч туманлараро фуқаролик суди',
    'Urganch tumanlararo fuqarolik sudi',
    'Ургенчский межрайонный гражданский суд'),
  D('fuq-shovot-tlf', 'khorezm',
    'Шовот туманлараро фуқаролик суди',
    'Shovot tumanlararo fuqarolik sudi',
    'Шаватский межрайонный гражданский суд'),
];

export function getDistrictCourtByCode(code: string): DistrictCourtDef | undefined {
  return DISTRICT_COURTS.find((d) => d.code === code);
}

/** All district courts for a (courtType, region) pair, in declared order. */
export function getDistrictCourtsFor(
  courtTypeCode: string,
  regionCode: string,
): DistrictCourtDef[] {
  return DISTRICT_COURTS.filter(
    (d) => d.courtTypeCode === courtTypeCode && d.regionCode === regionCode,
  );
}
