/* eslint-disable */
// AUTO-GENERATED by scripts/scrape-mhb.ts — do not edit by hand.
// Source: https://jadval2.sud.uz/jib/mhb/regions.html (administrative-offences schedule).
// Count: 219 courts. Schedule API: https://api5.sud.uz/{id}/{DDMMYYYY}

import type { DistrictCourtDef } from './district-courts';

export const MHB_COURTS: DistrictCourtDef[] = [
  {
    code: 'mhb-andijan-2',
    regionCode: 'andijan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Андижон вилоят суди',
      uz_latin: 'Andijon viloyat sudi',
      ru: 'Андижон вилоят суди',
    },
  },
  {
    code: 'mhb-andijan-22',
    regionCode: 'andijan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Андижон туман суди',
      uz_latin: 'Andijon tuman sudi',
      ru: 'Андижон туман суди',
    },
  },
  {
    code: 'mhb-andijan-21',
    regionCode: 'andijan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Андижон шаҳар суди',
      uz_latin: 'Andijon shahar sudi',
      ru: 'Андижон шаҳар суди',
    },
  },
  {
    code: 'mhb-andijan-23',
    regionCode: 'andijan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Асака туман суди',
      uz_latin: 'Asaka tuman sudi',
      ru: 'Асака туман суди',
    },
  },
  {
    code: 'mhb-andijan-24',
    regionCode: 'andijan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Балиқчи туман суди',
      uz_latin: 'Baliqchi tuman sudi',
      ru: 'Балиқчи туман суди',
    },
  },
  {
    code: 'mhb-andijan-25',
    regionCode: 'andijan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Булоқбоши туман суди',
      uz_latin: 'Buloqboshi tuman sudi',
      ru: 'Булоқбоши туман суди',
    },
  },
  {
    code: 'mhb-andijan-26',
    regionCode: 'andijan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Бўстон туман суди',
      uz_latin: 'Bo‘ston tuman sudi',
      ru: 'Бўстон туман суди',
    },
  },
  {
    code: 'mhb-andijan-153',
    regionCode: 'andijan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Жалақудуқ туман суди',
      uz_latin: 'Jalaquduq tuman sudi',
      ru: 'Жалақудуқ туман суди',
    },
  },
  {
    code: 'mhb-andijan-154',
    regionCode: 'andijan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Избоскан туман суди',
      uz_latin: 'Izboskan tuman sudi',
      ru: 'Избоскан туман суди',
    },
  },
  {
    code: 'mhb-andijan-155',
    regionCode: 'andijan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Қўрғонтепа туман суди',
      uz_latin: 'Qo‘rg‘ontepa tuman sudi',
      ru: 'Қўрғонтепа туман суди',
    },
  },
  {
    code: 'mhb-andijan-156',
    regionCode: 'andijan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Марҳамат туман суди',
      uz_latin: 'Marhamat tuman sudi',
      ru: 'Марҳамат туман суди',
    },
  },
  {
    code: 'mhb-andijan-157',
    regionCode: 'andijan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Олтинкўл туман суди',
      uz_latin: 'Oltinko‘l tuman sudi',
      ru: 'Олтинкўл туман суди',
    },
  },
  {
    code: 'mhb-andijan-158',
    regionCode: 'andijan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Пахтаобод туман суди',
      uz_latin: 'Paxtaobod tuman sudi',
      ru: 'Пахтаобод туман суди',
    },
  },
  {
    code: 'mhb-andijan-159',
    regionCode: 'andijan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Улуғнор туман суди',
      uz_latin: 'Ulug‘nor tuman sudi',
      ru: 'Улуғнор туман суди',
    },
  },
  {
    code: 'mhb-andijan-160',
    regionCode: 'andijan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Хонобод шаҳар суди',
      uz_latin: 'Xonobod shahar sudi',
      ru: 'Хонобод шаҳар суди',
    },
  },
  {
    code: 'mhb-andijan-161',
    regionCode: 'andijan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Хўжаобод туман суди',
      uz_latin: 'Xo‘jaobod tuman sudi',
      ru: 'Хўжаобод туман суди',
    },
  },
  {
    code: 'mhb-andijan-162',
    regionCode: 'andijan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Шаҳрихон туман суди',
      uz_latin: 'Shahrixon tuman sudi',
      ru: 'Шаҳрихон туман суди',
    },
  },
  {
    code: 'mhb-bukhara-3',
    regionCode: 'bukhara',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Бухоро вилоят суди',
      uz_latin: 'Buxoro viloyat sudi',
      ru: 'Бухоро вилоят суди',
    },
  },
  {
    code: 'mhb-bukhara-28',
    regionCode: 'bukhara',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Бухоро туман суди',
      uz_latin: 'Buxoro tuman sudi',
      ru: 'Бухоро туман суди',
    },
  },
  {
    code: 'mhb-bukhara-27',
    regionCode: 'bukhara',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Бухоро шаҳар суди',
      uz_latin: 'Buxoro shahar sudi',
      ru: 'Бухоро шаҳар суди',
    },
  },
  {
    code: 'mhb-bukhara-31',
    regionCode: 'bukhara',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Вобкент туман суди',
      uz_latin: 'Vobkent tuman sudi',
      ru: 'Вобкент туман суди',
    },
  },
  {
    code: 'mhb-bukhara-32',
    regionCode: 'bukhara',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Ғиждувон туман суди',
      uz_latin: 'G‘ijduvon tuman sudi',
      ru: 'Ғиждувон туман суди',
    },
  },
  {
    code: 'mhb-bukhara-178',
    regionCode: 'bukhara',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Жондор туман суди',
      uz_latin: 'Jondor tuman sudi',
      ru: 'Жондор туман суди',
    },
  },
  {
    code: 'mhb-bukhara-30',
    regionCode: 'bukhara',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Когон туман суди',
      uz_latin: 'Kogon tuman sudi',
      ru: 'Когон туман суди',
    },
  },
  {
    code: 'mhb-bukhara-29',
    regionCode: 'bukhara',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Когон шаҳар суди',
      uz_latin: 'Kogon shahar sudi',
      ru: 'Когон шаҳар суди',
    },
  },
  {
    code: 'mhb-bukhara-179',
    regionCode: 'bukhara',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Қоракўл туман суди',
      uz_latin: 'Qorako‘l tuman sudi',
      ru: 'Қоракўл туман суди',
    },
  },
  {
    code: 'mhb-bukhara-180',
    regionCode: 'bukhara',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Қоровулбозор туман суди',
      uz_latin: 'Qorovulbozor tuman sudi',
      ru: 'Қоровулбозор туман суди',
    },
  },
  {
    code: 'mhb-bukhara-181',
    regionCode: 'bukhara',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Олот туман суди',
      uz_latin: 'Olot tuman sudi',
      ru: 'Олот туман суди',
    },
  },
  {
    code: 'mhb-bukhara-182',
    regionCode: 'bukhara',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Пешку туман суди',
      uz_latin: 'Peshku tuman sudi',
      ru: 'Пешку туман суди',
    },
  },
  {
    code: 'mhb-bukhara-183',
    regionCode: 'bukhara',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Ромитан туман суди',
      uz_latin: 'Romitan tuman sudi',
      ru: 'Ромитан туман суди',
    },
  },
  {
    code: 'mhb-bukhara-184',
    regionCode: 'bukhara',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Шофиркон туман суди',
      uz_latin: 'Shofirkon tuman sudi',
      ru: 'Шофиркон туман суди',
    },
  },
  {
    code: 'mhb-jizzakh-5',
    regionCode: 'jizzakh',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Жиззах вилоят суди',
      uz_latin: 'Jizzax viloyat sudi',
      ru: 'Жиззах вилоят суди',
    },
  },
  {
    code: 'mhb-jizzakh-35',
    regionCode: 'jizzakh',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Арнасой туман суди',
      uz_latin: 'Arnasoy tuman sudi',
      ru: 'Арнасой туман суди',
    },
  },
  {
    code: 'mhb-jizzakh-36',
    regionCode: 'jizzakh',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Бахмал туман суди',
      uz_latin: 'Baxmal tuman sudi',
      ru: 'Бахмал туман суди',
    },
  },
  {
    code: 'mhb-jizzakh-37',
    regionCode: 'jizzakh',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Ғаллаорол туман суди',
      uz_latin: 'G‘allaorol tuman sudi',
      ru: 'Ғаллаорол туман суди',
    },
  },
  {
    code: 'mhb-jizzakh-115',
    regionCode: 'jizzakh',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Дўстлик туман суди',
      uz_latin: 'Do‘stlik tuman sudi',
      ru: 'Дўстлик туман суди',
    },
  },
  {
    code: 'mhb-jizzakh-33',
    regionCode: 'jizzakh',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Жиззах шаҳар суди',
      uz_latin: 'Jizzax shahar sudi',
      ru: 'Жиззах шаҳар суди',
    },
  },
  {
    code: 'mhb-jizzakh-117',
    regionCode: 'jizzakh',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Зарбдор туман суди',
      uz_latin: 'Zarbdor tuman sudi',
      ru: 'Зарбдор туман суди',
    },
  },
  {
    code: 'mhb-jizzakh-118',
    regionCode: 'jizzakh',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Зафаробод туман суди',
      uz_latin: 'Zafarobod tuman sudi',
      ru: 'Зафаробод туман суди',
    },
  },
  {
    code: 'mhb-jizzakh-116',
    regionCode: 'jizzakh',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Зомин туман суди',
      uz_latin: 'Zomin tuman sudi',
      ru: 'Зомин туман суди',
    },
  },
  {
    code: 'mhb-jizzakh-119',
    regionCode: 'jizzakh',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Мирзачўл туман суди',
      uz_latin: 'Mirzacho‘l tuman sudi',
      ru: 'Мирзачўл туман суди',
    },
  },
  {
    code: 'mhb-jizzakh-120',
    regionCode: 'jizzakh',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Пахтакор туман суди',
      uz_latin: 'Paxtakor tuman sudi',
      ru: 'Пахтакор туман суди',
    },
  },
  {
    code: 'mhb-jizzakh-121',
    regionCode: 'jizzakh',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Фориш туман суди',
      uz_latin: 'Forish tuman sudi',
      ru: 'Фориш туман суди',
    },
  },
  {
    code: 'mhb-jizzakh-34',
    regionCode: 'jizzakh',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Ш.Рашидов туман суди',
      uz_latin: 'Sh.Rashidov tuman sudi',
      ru: 'Ш.Рашидов туман суди',
    },
  },
  {
    code: 'mhb-jizzakh-122',
    regionCode: 'jizzakh',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Янгиобод туман суди',
      uz_latin: 'Yangiobod tuman sudi',
      ru: 'Янгиобод туман суди',
    },
  },
  {
    code: 'mhb-kashkadarya-13',
    regionCode: 'kashkadarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Қашқадарё вилоят суди',
      uz_latin: 'Qashqadaryo viloyat sudi',
      ru: 'Қашқадарё вилоят суди',
    },
  },
  {
    code: 'mhb-kashkadarya-42',
    regionCode: 'kashkadarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Ғузор туман суди',
      uz_latin: 'G‘uzor tuman sudi',
      ru: 'Ғузор туман суди',
    },
  },
  {
    code: 'mhb-kashkadarya-43',
    regionCode: 'kashkadarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Деҳқонобод туман суди',
      uz_latin: 'Dehqonobod tuman sudi',
      ru: 'Деҳқонобод туман суди',
    },
  },
  {
    code: 'mhb-kashkadarya-165',
    regionCode: 'kashkadarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Қамаши туман суди',
      uz_latin: 'Qamashi tuman sudi',
      ru: 'Қамаши туман суди',
    },
  },
  {
    code: 'mhb-kashkadarya-39',
    regionCode: 'kashkadarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Қарши туман суди',
      uz_latin: 'Qarshi tuman sudi',
      ru: 'Қарши туман суди',
    },
  },
  {
    code: 'mhb-kashkadarya-38',
    regionCode: 'kashkadarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Қарши шаҳар суди',
      uz_latin: 'Qarshi shahar sudi',
      ru: 'Қарши шаҳар суди',
    },
  },
  {
    code: 'mhb-kashkadarya-44',
    regionCode: 'kashkadarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Касби туман суди',
      uz_latin: 'Kasbi tuman sudi',
      ru: 'Касби туман суди',
    },
  },
  {
    code: 'mhb-kashkadarya-163',
    regionCode: 'kashkadarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Китоб туман суди',
      uz_latin: 'Kitob tuman sudi',
      ru: 'Китоб туман суди',
    },
  },
  {
    code: 'mhb-kashkadarya-164',
    regionCode: 'kashkadarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Косон туман суди',
      uz_latin: 'Koson tuman sudi',
      ru: 'Косон туман суди',
    },
  },
  {
    code: 'mhb-kashkadarya-166',
    regionCode: 'kashkadarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Миришкор туман суди',
      uz_latin: 'Mirishkor tuman sudi',
      ru: 'Миришкор туман суди',
    },
  },
  {
    code: 'mhb-kashkadarya-167',
    regionCode: 'kashkadarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Муборак туман суди',
      uz_latin: 'Muborak tuman sudi',
      ru: 'Муборак туман суди',
    },
  },
  {
    code: 'mhb-kashkadarya-168',
    regionCode: 'kashkadarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Нишон туман суди',
      uz_latin: 'Nishon tuman sudi',
      ru: 'Нишон туман суди',
    },
  },
  {
    code: 'mhb-kashkadarya-169',
    regionCode: 'kashkadarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Чироқчи туман суди',
      uz_latin: 'Chiroqchi tuman sudi',
      ru: 'Чироқчи туман суди',
    },
  },
  {
    code: 'mhb-kashkadarya-40',
    regionCode: 'kashkadarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Шаҳрисабз туман суди',
      uz_latin: 'Shahrisabz tuman sudi',
      ru: 'Шаҳрисабз туман суди',
    },
  },
  {
    code: 'mhb-kashkadarya-215',
    regionCode: 'kashkadarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Шахрисабз шаҳар суди',
      uz_latin: 'Shaxrisabz shahar sudi',
      ru: 'Шахрисабз шаҳар суди',
    },
  },
  {
    code: 'mhb-kashkadarya-41',
    regionCode: 'kashkadarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Яккабоғ туман суди',
      uz_latin: 'Yakkabog‘ tuman sudi',
      ru: 'Яккабоғ туман суди',
    },
  },
  {
    code: 'mhb-kashkadarya-220',
    regionCode: 'kashkadarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Кўкдала туман суди',
      uz_latin: 'Ko‘kdala tuman sudi',
      ru: 'Кўкдала туман суди',
    },
  },
  {
    code: 'mhb-karakalpakstan-4',
    regionCode: 'karakalpakstan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Қорақалпоғистон Республикаси суди',
      uz_latin: 'Qoraqalpog‘iston Respublikasi sudi',
      ru: 'Қорақалпоғистон Республикаси суди',
    },
  },
  {
    code: 'mhb-karakalpakstan-20',
    regionCode: 'karakalpakstan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Амударё туман суди',
      uz_latin: 'Amudaryo tuman sudi',
      ru: 'Амударё туман суди',
    },
  },
  {
    code: 'mhb-karakalpakstan-199',
    regionCode: 'karakalpakstan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Беруний туманлараро суди',
      uz_latin: 'Beruniy tumanlararo sudi',
      ru: 'Беруний туманлараро суди',
    },
  },
  {
    code: 'mhb-karakalpakstan-217',
    regionCode: 'karakalpakstan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Бўзатов туман суди',
      uz_latin: 'Bo‘zatov tuman sudi',
      ru: 'Бўзатов туман суди',
    },
  },
  {
    code: 'mhb-karakalpakstan-200',
    regionCode: 'karakalpakstan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Кегейли туман суди',
      uz_latin: 'Kegeyli tuman sudi',
      ru: 'Кегейли туман суди',
    },
  },
  {
    code: 'mhb-karakalpakstan-201',
    regionCode: 'karakalpakstan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Қонликўл туман суди',
      uz_latin: 'Qonliko‘l tuman sudi',
      ru: 'Қонликўл туман суди',
    },
  },
  {
    code: 'mhb-karakalpakstan-202',
    regionCode: 'karakalpakstan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Қораўзак туман суди',
      uz_latin: 'Qorao‘zak tuman sudi',
      ru: 'Қораўзак туман суди',
    },
  },
  {
    code: 'mhb-karakalpakstan-18',
    regionCode: 'karakalpakstan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Қонликўл туман суди',
      uz_latin: 'Qonliko‘l tuman sudi',
      ru: 'Қонликўл туман суди',
    },
  },
  {
    code: 'mhb-karakalpakstan-203',
    regionCode: 'karakalpakstan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Мўйноқ туман суди',
      uz_latin: 'Mo‘ynoq tuman sudi',
      ru: 'Мўйноқ туман суди',
    },
  },
  {
    code: 'mhb-karakalpakstan-17',
    regionCode: 'karakalpakstan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Нукус туман суди',
      uz_latin: 'Nukus tuman sudi',
      ru: 'Нукус туман суди',
    },
  },
  {
    code: 'mhb-karakalpakstan-16',
    regionCode: 'karakalpakstan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Нукус шаҳар суди',
      uz_latin: 'Nukus shahar sudi',
      ru: 'Нукус шаҳар суди',
    },
  },
  {
    code: 'mhb-karakalpakstan-204',
    regionCode: 'karakalpakstan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Тахиатош туман суди',
      uz_latin: 'Taxiatosh tuman sudi',
      ru: 'Тахиатош туман суди',
    },
  },
  {
    code: 'mhb-karakalpakstan-205',
    regionCode: 'karakalpakstan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Тахтакўпир туман суди',
      uz_latin: 'Taxtako‘pir tuman sudi',
      ru: 'Тахтакўпир туман суди',
    },
  },
  {
    code: 'mhb-karakalpakstan-206',
    regionCode: 'karakalpakstan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Тўрткўл туман суди',
      uz_latin: 'To‘rtko‘l tuman sudi',
      ru: 'Тўрткўл туман суди',
    },
  },
  {
    code: 'mhb-karakalpakstan-207',
    regionCode: 'karakalpakstan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Хўжайли туман суди',
      uz_latin: 'Xo‘jayli tuman sudi',
      ru: 'Хўжайли туман суди',
    },
  },
  {
    code: 'mhb-karakalpakstan-19',
    regionCode: 'karakalpakstan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Чимбой туман суди',
      uz_latin: 'Chimboy tuman sudi',
      ru: 'Чимбой туман суди',
    },
  },
  {
    code: 'mhb-karakalpakstan-208',
    regionCode: 'karakalpakstan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Шуманай туман суди',
      uz_latin: 'Shumanay tuman sudi',
      ru: 'Шуманай туман суди',
    },
  },
  {
    code: 'mhb-karakalpakstan-209',
    regionCode: 'karakalpakstan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Элликқалъа туман суди',
      uz_latin: 'Ellikqal’a tuman sudi',
      ru: 'Элликқалъа туман суди',
    },
  },
  {
    code: 'mhb-navoi-6',
    regionCode: 'navoi',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Навоий вилоят суди',
      uz_latin: 'Navoiy viloyat sudi',
      ru: 'Навоий вилоят суди',
    },
  },
  {
    code: 'mhb-navoi-46',
    regionCode: 'navoi',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Зарафшон шаҳар суди',
      uz_latin: 'Zarafshon shahar sudi',
      ru: 'Зарафшон шаҳар суди',
    },
  },
  {
    code: 'mhb-navoi-47',
    regionCode: 'navoi',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Кармана туман суди',
      uz_latin: 'Karmana tuman sudi',
      ru: 'Кармана туман суди',
    },
  },
  {
    code: 'mhb-navoi-185',
    regionCode: 'navoi',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Қизилтепа туман суди',
      uz_latin: 'Qiziltepa tuman sudi',
      ru: 'Қизилтепа туман суди',
    },
  },
  {
    code: 'mhb-navoi-48',
    regionCode: 'navoi',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Конимех туман суди',
      uz_latin: 'Konimex tuman sudi',
      ru: 'Конимех туман суди',
    },
  },
  {
    code: 'mhb-navoi-186',
    regionCode: 'navoi',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Навбаҳор туман суди',
      uz_latin: 'Navbahor tuman sudi',
      ru: 'Навбаҳор туман суди',
    },
  },
  {
    code: 'mhb-navoi-45',
    regionCode: 'navoi',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Навоий шаҳар суди',
      uz_latin: 'Navoiy shahar sudi',
      ru: 'Навоий шаҳар суди',
    },
  },
  {
    code: 'mhb-navoi-187',
    regionCode: 'navoi',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Нурота туман суди',
      uz_latin: 'Nurota tuman sudi',
      ru: 'Нурота туман суди',
    },
  },
  {
    code: 'mhb-navoi-188',
    regionCode: 'navoi',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Томди туман суди',
      uz_latin: 'Tomdi tuman sudi',
      ru: 'Томди туман суди',
    },
  },
  {
    code: 'mhb-navoi-189',
    regionCode: 'navoi',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Учқудуқ туман суди',
      uz_latin: 'Uchquduq tuman sudi',
      ru: 'Учқудуқ туман суди',
    },
  },
  {
    code: 'mhb-navoi-190',
    regionCode: 'navoi',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Хатирчи туман суди',
      uz_latin: 'Xatirchi tuman sudi',
      ru: 'Хатирчи туман суди',
    },
  },
  {
    code: 'mhb-namangan-7',
    regionCode: 'namangan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Наманган вилоят суди',
      uz_latin: 'Namangan viloyat sudi',
      ru: 'Наманган вилоят суди',
    },
  },
  {
    code: 'mhb-namangan-51',
    regionCode: 'namangan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Косонсой туман суди',
      uz_latin: 'Kosonsoy tuman sudi',
      ru: 'Косонсой туман суди',
    },
  },
  {
    code: 'mhb-namangan-52',
    regionCode: 'namangan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Мингбулоқ туман суди',
      uz_latin: 'Mingbuloq tuman sudi',
      ru: 'Мингбулоқ туман суди',
    },
  },
  {
    code: 'mhb-namangan-50',
    regionCode: 'namangan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'ЧНаманган туман суди',
      uz_latin: 'CHNamangan tuman sudi',
      ru: 'ЧНаманган туман суди',
    },
  },
  {
    code: 'mhb-namangan-49',
    regionCode: 'namangan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Наманган шаҳар суди',
      uz_latin: 'Namangan shahar sudi',
      ru: 'Наманган шаҳар суди',
    },
  },
  {
    code: 'mhb-namangan-145',
    regionCode: 'namangan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Норин туман суди',
      uz_latin: 'Norin tuman sudi',
      ru: 'Норин туман суди',
    },
  },
  {
    code: 'mhb-namangan-146',
    regionCode: 'namangan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Поп туман суди',
      uz_latin: 'Pop tuman sudi',
      ru: 'Поп туман суди',
    },
  },
  {
    code: 'mhb-namangan-147',
    regionCode: 'namangan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Тўрақўрғон туман суди',
      uz_latin: 'To‘raqo‘rg‘on tuman sudi',
      ru: 'Тўрақўрғон туман суди',
    },
  },
  {
    code: 'mhb-namangan-148',
    regionCode: 'namangan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Уйчи туман суди',
      uz_latin: 'Uychi tuman sudi',
      ru: 'Уйчи туман суди',
    },
  },
  {
    code: 'mhb-namangan-149',
    regionCode: 'namangan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Учқўрғон туман суди',
      uz_latin: 'Uchqo‘rg‘on tuman sudi',
      ru: 'Учқўрғон туман суди',
    },
  },
  {
    code: 'mhb-namangan-150',
    regionCode: 'namangan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Чортоқ туман суди',
      uz_latin: 'Chortoq tuman sudi',
      ru: 'Чортоқ туман суди',
    },
  },
  {
    code: 'mhb-namangan-151',
    regionCode: 'namangan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Чуст туман суди',
      uz_latin: 'Chust tuman sudi',
      ru: 'Чуст туман суди',
    },
  },
  {
    code: 'mhb-namangan-152',
    regionCode: 'namangan',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Янгиқўрғон туман суди',
      uz_latin: 'Yangiqo‘rg‘on tuman sudi',
      ru: 'Янгиқўрғон туман суди',
    },
  },
  {
    code: 'mhb-samarkand-8',
    regionCode: 'samarkand',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Самарқанд вилоят суди',
      uz_latin: 'Samarqand viloyat sudi',
      ru: 'Самарқанд вилоят суди',
    },
  },
  {
    code: 'mhb-samarkand-57',
    regionCode: 'samarkand',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Булунғур туман суди',
      uz_latin: 'Bulung‘ur tuman sudi',
      ru: 'Булунғур туман суди',
    },
  },
  {
    code: 'mhb-samarkand-58',
    regionCode: 'samarkand',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Жомбой туман суди',
      uz_latin: 'Jomboy tuman sudi',
      ru: 'Жомбой туман суди',
    },
  },
  {
    code: 'mhb-samarkand-59',
    regionCode: 'samarkand',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Иштихон туман суди',
      uz_latin: 'Ishtixon tuman sudi',
      ru: 'Иштихон туман суди',
    },
  },
  {
    code: 'mhb-samarkand-56',
    regionCode: 'samarkand',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Каттақўрғон туман суди',
      uz_latin: 'Kattaqo‘rg‘on tuman sudi',
      ru: 'Каттақўрғон туман суди',
    },
  },
  {
    code: 'mhb-samarkand-55',
    regionCode: 'samarkand',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Каттақўрғон шаҳар суди',
      uz_latin: 'Kattaqo‘rg‘on shahar sudi',
      ru: 'Каттақўрғон шаҳар суди',
    },
  },
  {
    code: 'mhb-samarkand-60',
    regionCode: 'samarkand',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Қўшрабод туман суди',
      uz_latin: 'Qo‘shrabod tuman sudi',
      ru: 'Қўшрабод туман суди',
    },
  },
  {
    code: 'mhb-samarkand-123',
    regionCode: 'samarkand',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Нарпай туман суди',
      uz_latin: 'Narpay tuman sudi',
      ru: 'Нарпай туман суди',
    },
  },
  {
    code: 'mhb-samarkand-124',
    regionCode: 'samarkand',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Нуробод туман суди',
      uz_latin: 'Nurobod tuman sudi',
      ru: 'Нуробод туман суди',
    },
  },
  {
    code: 'mhb-samarkand-125',
    regionCode: 'samarkand',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Оқдарё туман суди',
      uz_latin: 'Oqdaryo tuman sudi',
      ru: 'Оқдарё туман суди',
    },
  },
  {
    code: 'mhb-samarkand-126',
    regionCode: 'samarkand',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Пайариқ туман суди',
      uz_latin: 'Payariq tuman sudi',
      ru: 'Пайариқ туман суди',
    },
  },
  {
    code: 'mhb-samarkand-127',
    regionCode: 'samarkand',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Пастдарғом туман суди',
      uz_latin: 'Pastdarg‘om tuman sudi',
      ru: 'Пастдарғом туман суди',
    },
  },
  {
    code: 'mhb-samarkand-128',
    regionCode: 'samarkand',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Пахтачи туман суди',
      uz_latin: 'Paxtachi tuman sudi',
      ru: 'Пахтачи туман суди',
    },
  },
  {
    code: 'mhb-samarkand-54',
    regionCode: 'samarkand',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Самарқанд туман суди',
      uz_latin: 'Samarqand tuman sudi',
      ru: 'Самарқанд туман суди',
    },
  },
  {
    code: 'mhb-samarkand-53',
    regionCode: 'samarkand',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Самарқанд шаҳар суди',
      uz_latin: 'Samarqand shahar sudi',
      ru: 'Самарқанд шаҳар суди',
    },
  },
  {
    code: 'mhb-samarkand-129',
    regionCode: 'samarkand',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Тойлоқ туман суди',
      uz_latin: 'Toyloq tuman sudi',
      ru: 'Тойлоқ туман суди',
    },
  },
  {
    code: 'mhb-samarkand-130',
    regionCode: 'samarkand',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Ургут туман суди',
      uz_latin: 'Urgut tuman sudi',
      ru: 'Ургут туман суди',
    },
  },
  {
    code: 'mhb-syrdarya-9',
    regionCode: 'syrdarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Сирдарё вилоят суди',
      uz_latin: 'Sirdaryo viloyat sudi',
      ru: 'Сирдарё вилоят суди',
    },
  },
  {
    code: 'mhb-syrdarya-69',
    regionCode: 'syrdarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Боёвут туман суди',
      uz_latin: 'Boyovut tuman sudi',
      ru: 'Боёвут туман суди',
    },
  },
  {
    code: 'mhb-syrdarya-68',
    regionCode: 'syrdarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Гулистон туман суди',
      uz_latin: 'Guliston tuman sudi',
      ru: 'Гулистон туман суди',
    },
  },
  {
    code: 'mhb-syrdarya-67',
    regionCode: 'syrdarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Гулистон шаҳар суди',
      uz_latin: 'Guliston shahar sudi',
      ru: 'Гулистон шаҳар суди',
    },
  },
  {
    code: 'mhb-syrdarya-70',
    regionCode: 'syrdarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Мирзаобод туман суди',
      uz_latin: 'Mirzaobod tuman sudi',
      ru: 'Мирзаобод туман суди',
    },
  },
  {
    code: 'mhb-syrdarya-108',
    regionCode: 'syrdarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Оқолтин туман суди',
      uz_latin: 'Oqoltin tuman sudi',
      ru: 'Оқолтин туман суди',
    },
  },
  {
    code: 'mhb-syrdarya-109',
    regionCode: 'syrdarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Сайхунобод туман суди',
      uz_latin: 'Sayxunobod tuman sudi',
      ru: 'Сайхунобод туман суди',
    },
  },
  {
    code: 'mhb-syrdarya-110',
    regionCode: 'syrdarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Сардоба туман суди',
      uz_latin: 'Sardoba tuman sudi',
      ru: 'Сардоба туман суди',
    },
  },
  {
    code: 'mhb-syrdarya-111',
    regionCode: 'syrdarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Сирдарё туман суди',
      uz_latin: 'Sirdaryo tuman sudi',
      ru: 'Сирдарё туман суди',
    },
  },
  {
    code: 'mhb-syrdarya-112',
    regionCode: 'syrdarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Ховос туман суди',
      uz_latin: 'Xovos tuman sudi',
      ru: 'Ховос туман суди',
    },
  },
  {
    code: 'mhb-syrdarya-113',
    regionCode: 'syrdarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Ширин шаҳар суди',
      uz_latin: 'Shirin shahar sudi',
      ru: 'Ширин шаҳар суди',
    },
  },
  {
    code: 'mhb-syrdarya-114',
    regionCode: 'syrdarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Янгиер шаҳар суди',
      uz_latin: 'Yangier shahar sudi',
      ru: 'Янгиер шаҳар суди',
    },
  },
  {
    code: 'mhb-surkhandarya-10',
    regionCode: 'surkhandarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Сурхондарё вилоят суди',
      uz_latin: 'Surxondaryo viloyat sudi',
      ru: 'Сурхондарё вилоят суди',
    },
  },
  {
    code: 'mhb-surkhandarya-63',
    regionCode: 'surkhandarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Ангор туман суди',
      uz_latin: 'Angor tuman sudi',
      ru: 'Ангор туман суди',
    },
  },
  {
    code: 'mhb-surkhandarya-216',
    regionCode: 'surkhandarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Бандихон туман суди',
      uz_latin: 'Bandixon tuman sudi',
      ru: 'Бандихон туман суди',
    },
  },
  {
    code: 'mhb-surkhandarya-64',
    regionCode: 'surkhandarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Бойсун туман суди',
      uz_latin: 'Boysun tuman sudi',
      ru: 'Бойсун туман суди',
    },
  },
  {
    code: 'mhb-surkhandarya-65',
    regionCode: 'surkhandarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Денов туман суди',
      uz_latin: 'Denov tuman sudi',
      ru: 'Денов туман суди',
    },
  },
  {
    code: 'mhb-surkhandarya-66',
    regionCode: 'surkhandarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Жарқўрғон туман суди',
      uz_latin: 'Jarqo‘rg‘on tuman sudi',
      ru: 'Жарқўрғон туман суди',
    },
  },
  {
    code: 'mhb-surkhandarya-170',
    regionCode: 'surkhandarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Қизириқ туман суди',
      uz_latin: 'Qiziriq tuman sudi',
      ru: 'Қизириқ туман суди',
    },
  },
  {
    code: 'mhb-surkhandarya-171',
    regionCode: 'surkhandarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Қумқўрғон туман суди',
      uz_latin: 'Qumqo‘rg‘on tuman sudi',
      ru: 'Қумқўрғон туман суди',
    },
  },
  {
    code: 'mhb-surkhandarya-172',
    regionCode: 'surkhandarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Музработ туман суди',
      uz_latin: 'Muzrabot tuman sudi',
      ru: 'Музработ туман суди',
    },
  },
  {
    code: 'mhb-surkhandarya-173',
    regionCode: 'surkhandarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Олтинсой туман суди',
      uz_latin: 'Oltinsoy tuman sudi',
      ru: 'Олтинсой туман суди',
    },
  },
  {
    code: 'mhb-surkhandarya-174',
    regionCode: 'surkhandarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Сариосиё туман суди',
      uz_latin: 'Sariosiyo tuman sudi',
      ru: 'Сариосиё туман суди',
    },
  },
  {
    code: 'mhb-surkhandarya-62',
    regionCode: 'surkhandarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Термиз туман суди',
      uz_latin: 'Termiz tuman sudi',
      ru: 'Термиз туман суди',
    },
  },
  {
    code: 'mhb-surkhandarya-61',
    regionCode: 'surkhandarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Термиз шаҳар суди',
      uz_latin: 'Termiz shahar sudi',
      ru: 'Термиз шаҳар суди',
    },
  },
  {
    code: 'mhb-surkhandarya-175',
    regionCode: 'surkhandarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Узун туман суди',
      uz_latin: 'Uzun tuman sudi',
      ru: 'Узун туман суди',
    },
  },
  {
    code: 'mhb-surkhandarya-176',
    regionCode: 'surkhandarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Шеробод туман суди',
      uz_latin: 'Sherobod tuman sudi',
      ru: 'Шеробод туман суди',
    },
  },
  {
    code: 'mhb-surkhandarya-177',
    regionCode: 'surkhandarya',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Шўрчи туман суди',
      uz_latin: 'Sho‘rchi tuman sudi',
      ru: 'Шўрчи туман суди',
    },
  },
  {
    code: 'mhb-tashkent_region-14',
    regionCode: 'tashkent_region',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Тошкент вилоят суди',
      uz_latin: 'Toshkent viloyat sudi',
      ru: 'Тошкент вилоят суди',
    },
  },
  {
    code: 'mhb-tashkent_region-74',
    regionCode: 'tashkent_region',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Ангрен шаҳар суди',
      uz_latin: 'Angren shahar sudi',
      ru: 'Ангрен шаҳар суди',
    },
  },
  {
    code: 'mhb-tashkent_region-73',
    regionCode: 'tashkent_region',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Бекобод туман суди',
      uz_latin: 'Bekobod tuman sudi',
      ru: 'Бекобод туман суди',
    },
  },
  {
    code: 'mhb-tashkent_region-72',
    regionCode: 'tashkent_region',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Бекобод шаҳар суди',
      uz_latin: 'Bekobod shahar sudi',
      ru: 'Бекобод шаҳар суди',
    },
  },
  {
    code: 'mhb-tashkent_region-75',
    regionCode: 'tashkent_region',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Бўка туман суди',
      uz_latin: 'Bo‘ka tuman sudi',
      ru: 'Бўка туман суди',
    },
  },
  {
    code: 'mhb-tashkent_region-76',
    regionCode: 'tashkent_region',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Бўстонлиқ туман суди',
      uz_latin: 'Bo‘stonliq tuman sudi',
      ru: 'Бўстонлиқ туман суди',
    },
  },
  {
    code: 'mhb-tashkent_region-71',
    regionCode: 'tashkent_region',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Зангиота туман суди',
      uz_latin: 'Zangiota tuman sudi',
      ru: 'Зангиота туман суди',
    },
  },
  {
    code: 'mhb-tashkent_region-77',
    regionCode: 'tashkent_region',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Қибрай туман суди',
      uz_latin: 'Qibray tuman sudi',
      ru: 'Қибрай туман суди',
    },
  },
  {
    code: 'mhb-tashkent_region-97',
    regionCode: 'tashkent_region',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Қуйи Чирчиқ туман суди',
      uz_latin: 'Quyi Chirchiq tuman sudi',
      ru: 'Қуйи Чирчиқ туман суди',
    },
  },
  {
    code: 'mhb-tashkent_region-213',
    regionCode: 'tashkent_region',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Нурафшон шаҳар суди',
      uz_latin: 'Nurafshon shahar sudi',
      ru: 'Нурафшон шаҳар суди',
    },
  },
  {
    code: 'mhb-tashkent_region-98',
    regionCode: 'tashkent_region',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Оққўрғон туман суди',
      uz_latin: 'Oqqo‘rg‘on tuman sudi',
      ru: 'Оққўрғон туман суди',
    },
  },
  {
    code: 'mhb-tashkent_region-99',
    regionCode: 'tashkent_region',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Олмалиқ шаҳар суди',
      uz_latin: 'Olmaliq shahar sudi',
      ru: 'Олмалиқ шаҳар суди',
    },
  },
  {
    code: 'mhb-tashkent_region-100',
    regionCode: 'tashkent_region',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Оҳангарон туман суди',
      uz_latin: 'Ohangaron tuman sudi',
      ru: 'Оҳангарон туман суди',
    },
  },
  {
    code: 'mhb-tashkent_region-212',
    regionCode: 'tashkent_region',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Оҳангарон шаҳар суди',
      uz_latin: 'Ohangaron shahar sudi',
      ru: 'Оҳангарон шаҳар суди',
    },
  },
  {
    code: 'mhb-tashkent_region-101',
    regionCode: 'tashkent_region',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Паркент туман суди',
      uz_latin: 'Parkent tuman sudi',
      ru: 'Паркент туман суди',
    },
  },
  {
    code: 'mhb-tashkent_region-102',
    regionCode: 'tashkent_region',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Пискент туман суди',
      uz_latin: 'Piskent tuman sudi',
      ru: 'Пискент туман суди',
    },
  },
  {
    code: 'mhb-tashkent_region-214',
    regionCode: 'tashkent_region',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Тошкент туман суди',
      uz_latin: 'Toshkent tuman sudi',
      ru: 'Тошкент туман суди',
    },
  },
  {
    code: 'mhb-tashkent_region-103',
    regionCode: 'tashkent_region',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Ўрта Чирчиқ туман суди',
      uz_latin: 'O‘rta Chirchiq tuman sudi',
      ru: 'Ўрта Чирчиқ туман суди',
    },
  },
  {
    code: 'mhb-tashkent_region-104',
    regionCode: 'tashkent_region',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Чиноз туман суди',
      uz_latin: 'Chinoz tuman sudi',
      ru: 'Чиноз туман суди',
    },
  },
  {
    code: 'mhb-tashkent_region-105',
    regionCode: 'tashkent_region',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Чирчиқ шаҳар суди',
      uz_latin: 'Chirchiq shahar sudi',
      ru: 'Чирчиқ шаҳар суди',
    },
  },
  {
    code: 'mhb-tashkent_region-106',
    regionCode: 'tashkent_region',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Юқори Чирчиқ туман суди',
      uz_latin: 'Yuqori Chirchiq tuman sudi',
      ru: 'Юқори Чирчиқ туман суди',
    },
  },
  {
    code: 'mhb-tashkent_region-107',
    regionCode: 'tashkent_region',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Янгийўл туман суди',
      uz_latin: 'Yangiyo‘l tuman sudi',
      ru: 'Янгийўл туман суди',
    },
  },
  {
    code: 'mhb-tashkent_region-211',
    regionCode: 'tashkent_region',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Янгийўл шаҳар суди',
      uz_latin: 'Yangiyo‘l shahar sudi',
      ru: 'Янгийўл шаҳар суди',
    },
  },
  {
    code: 'mhb-tashkent_city-1',
    regionCode: 'tashkent_city',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Тошкент шаҳар суди',
      uz_latin: 'Toshkent shahar sudi',
      ru: 'Тошкент шаҳар суди',
    },
  },
  {
    code: 'mhb-tashkent_city-95',
    regionCode: 'tashkent_city',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Бектемир туман суди',
      uz_latin: 'Bektemir tuman sudi',
      ru: 'Бектемир туман суди',
    },
  },
  {
    code: 'mhb-tashkent_city-78',
    regionCode: 'tashkent_city',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Мирзо Улуғбек туман суди',
      uz_latin: 'Mirzo Ulug‘bek tuman sudi',
      ru: 'Мирзо Улуғбек туман суди',
    },
  },
  {
    code: 'mhb-tashkent_city-87',
    regionCode: 'tashkent_city',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Миробод туман суди',
      uz_latin: 'Mirobod tuman sudi',
      ru: 'Миробод туман суди',
    },
  },
  {
    code: 'mhb-tashkent_city-93',
    regionCode: 'tashkent_city',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Олмазор туман суди',
      uz_latin: 'Olmazor tuman sudi',
      ru: 'Олмазор туман суди',
    },
  },
  {
    code: 'mhb-tashkent_city-96',
    regionCode: 'tashkent_city',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Сергели туман суди',
      uz_latin: 'Sergeli tuman sudi',
      ru: 'Сергели туман суди',
    },
  },
  {
    code: 'mhb-tashkent_city-92',
    regionCode: 'tashkent_city',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Учтепа туман суди',
      uz_latin: 'Uchtepa tuman sudi',
      ru: 'Учтепа туман суди',
    },
  },
  {
    code: 'mhb-tashkent_city-91',
    regionCode: 'tashkent_city',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Чилонзор туман суди',
      uz_latin: 'Chilonzor tuman sudi',
      ru: 'Чилонзор туман суди',
    },
  },
  {
    code: 'mhb-tashkent_city-88',
    regionCode: 'tashkent_city',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Шайхантохур туман суди',
      uz_latin: 'Shayxantoxur tuman sudi',
      ru: 'Шайхантохур туман суди',
    },
  },
  {
    code: 'mhb-tashkent_city-89',
    regionCode: 'tashkent_city',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Юнусобод туман суди',
      uz_latin: 'Yunusobod tuman sudi',
      ru: 'Юнусобод туман суди',
    },
  },
  {
    code: 'mhb-tashkent_city-90',
    regionCode: 'tashkent_city',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Яккасарой туман суди',
      uz_latin: 'Yakkasaroy tuman sudi',
      ru: 'Яккасарой туман суди',
    },
  },
  {
    code: 'mhb-tashkent_city-219',
    regionCode: 'tashkent_city',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Янгиҳаёт туман суди',
      uz_latin: 'Yangihayot tuman sudi',
      ru: 'Янгиҳаёт туман суди',
    },
  },
  {
    code: 'mhb-tashkent_city-94',
    regionCode: 'tashkent_city',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Яшнобод туман суди',
      uz_latin: 'Yashnobod tuman sudi',
      ru: 'Яшнобод туман суди',
    },
  },
  {
    code: 'mhb-fergana-11',
    regionCode: 'fergana',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Фарғона вилоят суди',
      uz_latin: 'Farg‘ona viloyat sudi',
      ru: 'Фарғона вилоят суди',
    },
  },
  {
    code: 'mhb-fergana-131',
    regionCode: 'fergana',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Бешариқ туман суди',
      uz_latin: 'Beshariq tuman sudi',
      ru: 'Бешариқ туман суди',
    },
  },
  {
    code: 'mhb-fergana-132',
    regionCode: 'fergana',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Боғдод туман суди',
      uz_latin: 'Bog‘dod tuman sudi',
      ru: 'Боғдод туман суди',
    },
  },
  {
    code: 'mhb-fergana-133',
    regionCode: 'fergana',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Бувайда туман суди',
      uz_latin: 'Buvayda tuman sudi',
      ru: 'Бувайда туман суди',
    },
  },
  {
    code: 'mhb-fergana-134',
    regionCode: 'fergana',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Данғара туман суди',
      uz_latin: 'Dang‘ara tuman sudi',
      ru: 'Данғара туман суди',
    },
  },
  {
    code: 'mhb-fergana-135',
    regionCode: 'fergana',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Ёзъёвон туман суди',
      uz_latin: 'Yoz’yovon tuman sudi',
      ru: 'Ёзъёвон туман суди',
    },
  },
  {
    code: 'mhb-fergana-83',
    regionCode: 'fergana',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Қувасой шаҳар суди',
      uz_latin: 'Quvasoy shahar sudi',
      ru: 'Қувасой шаҳар суди',
    },
  },
  {
    code: 'mhb-fergana-136',
    regionCode: 'fergana',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Қува туман суди',
      uz_latin: 'Quva tuman sudi',
      ru: 'Қува туман суди',
    },
  },
  {
    code: 'mhb-fergana-81',
    regionCode: 'fergana',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Қўқон шаҳар суди',
      uz_latin: 'Qo‘qon shahar sudi',
      ru: 'Қўқон шаҳар суди',
    },
  },
  {
    code: 'mhb-fergana-137',
    regionCode: 'fergana',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Қўштепа туман суди',
      uz_latin: 'Qo‘shtepa tuman sudi',
      ru: 'Қўштепа туман суди',
    },
  },
  {
    code: 'mhb-fergana-138',
    regionCode: 'fergana',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Марғилон шаҳар суди',
      uz_latin: 'Marg‘ilon shahar sudi',
      ru: 'Марғилон шаҳар суди',
    },
  },
  {
    code: 'mhb-fergana-139',
    regionCode: 'fergana',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Олтиариқ туман суди',
      uz_latin: 'Oltiariq tuman sudi',
      ru: 'Олтиариқ туман суди',
    },
  },
  {
    code: 'mhb-fergana-140',
    regionCode: 'fergana',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Риштон туман суди',
      uz_latin: 'Rishton tuman sudi',
      ru: 'Риштон туман суди',
    },
  },
  {
    code: 'mhb-fergana-141',
    regionCode: 'fergana',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Сўх туман суди',
      uz_latin: 'So‘x tuman sudi',
      ru: 'Сўх туман суди',
    },
  },
  {
    code: 'mhb-fergana-142',
    regionCode: 'fergana',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Тошлоқ туман суди',
      uz_latin: 'Toshloq tuman sudi',
      ru: 'Тошлоқ туман суди',
    },
  },
  {
    code: 'mhb-fergana-143',
    regionCode: 'fergana',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Учкўприк туман суди',
      uz_latin: 'Uchko‘prik tuman sudi',
      ru: 'Учкўприк туман суди',
    },
  },
  {
    code: 'mhb-fergana-82',
    regionCode: 'fergana',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Ўзбекистон туман суди',
      uz_latin: 'O‘zbekiston tuman sudi',
      ru: 'Ўзбекистон туман суди',
    },
  },
  {
    code: 'mhb-fergana-80',
    regionCode: 'fergana',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Фарғона туман суди',
      uz_latin: 'Farg‘ona tuman sudi',
      ru: 'Фарғона туман суди',
    },
  },
  {
    code: 'mhb-fergana-79',
    regionCode: 'fergana',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Фарғона шаҳар суди',
      uz_latin: 'Farg‘ona shahar sudi',
      ru: 'Фарғона шаҳар суди',
    },
  },
  {
    code: 'mhb-fergana-144',
    regionCode: 'fergana',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Фурқат туман суди',
      uz_latin: 'Furqat tuman sudi',
      ru: 'Фурқат туман суди',
    },
  },
  {
    code: 'mhb-khorezm-12',
    regionCode: 'khorezm',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Хоразм вилоят суди',
      uz_latin: 'Xorazm viloyat sudi',
      ru: 'Хоразм вилоят суди',
    },
  },
  {
    code: 'mhb-khorezm-192',
    regionCode: 'khorezm',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Боғот туман суди',
      uz_latin: 'Bog‘ot tuman sudi',
      ru: 'Боғот туман суди',
    },
  },
  {
    code: 'mhb-khorezm-193',
    regionCode: 'khorezm',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Гурлан туман суди',
      uz_latin: 'Gurlan tuman sudi',
      ru: 'Гурлан туман суди',
    },
  },
  {
    code: 'mhb-khorezm-194',
    regionCode: 'khorezm',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Қўшкўпир туман суди',
      uz_latin: 'Qo‘shko‘pir tuman sudi',
      ru: 'Қўшкўпир туман суди',
    },
  },
  {
    code: 'mhb-khorezm-218',
    regionCode: 'khorezm',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Тупроққалъа туман суди',
      uz_latin: 'Tuproqqal’a tuman sudi',
      ru: 'Тупроққалъа туман суди',
    },
  },
  {
    code: 'mhb-khorezm-85',
    regionCode: 'khorezm',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Урганч туман суди',
      uz_latin: 'Urganch tuman sudi',
      ru: 'Урганч туман суди',
    },
  },
  {
    code: 'mhb-khorezm-84',
    regionCode: 'khorezm',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Урганч шаҳар суди',
      uz_latin: 'Urganch shahar sudi',
      ru: 'Урганч шаҳар суди',
    },
  },
  {
    code: 'mhb-khorezm-195',
    regionCode: 'khorezm',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Хазорасп туман суди',
      uz_latin: 'Xazorasp tuman sudi',
      ru: 'Хазорасп туман суди',
    },
  },
  {
    code: 'mhb-khorezm-86',
    regionCode: 'khorezm',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Хива туман суди',
      uz_latin: 'Xiva tuman sudi',
      ru: 'Хива туман суди',
    },
  },
  {
    code: 'mhb-khorezm-215',
    regionCode: 'khorezm',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Хива шаҳар суди',
      uz_latin: 'Xiva shahar sudi',
      ru: 'Хива шаҳар суди',
    },
  },
  {
    code: 'mhb-khorezm-196',
    regionCode: 'khorezm',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Хонқа туман суди',
      uz_latin: 'Xonqa tuman sudi',
      ru: 'Хонқа туман суди',
    },
  },
  {
    code: 'mhb-khorezm-191',
    regionCode: 'khorezm',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Шовот туман суди',
      uz_latin: 'Shovot tuman sudi',
      ru: 'Шовот туман суди',
    },
  },
  {
    code: 'mhb-khorezm-197',
    regionCode: 'khorezm',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Янгиариқ туман суди',
      uz_latin: 'Yangiariq tuman sudi',
      ru: 'Янгиариқ туман суди',
    },
  },
  {
    code: 'mhb-khorezm-198',
    regionCode: 'khorezm',
    courtTypeCode: 'mhb',
    name: {
      uz_cyrillic: 'Янгибозор туман суди',
      uz_latin: 'Yangibozor tuman sudi',
      ru: 'Янгибозор туман суди',
    },
  },
];
