#!/usr/bin/env bash
# Provision a persistent Cloudflare named tunnel for the bot's
# Mini App, plus systemd unit + .env wiring. One-shot installer —
# safe to re-run (existing tunnel + creds are reused).
#
# Usage (run on the server, as root):
#   sudo bash deploy/setup-cloudflared.sh <hostname>
#
# Example:
#   sudo bash deploy/setup-cloudflared.sh ariza.mysite.uz
#
# Prerequisites:
#   - You own a domain (any registrar) and its nameservers are pointed
#     at Cloudflare. To check: `dig NS yourdomain.com` should return
#     *.ns.cloudflare.com. Move the domain to Cloudflare first if not:
#     https://developers.cloudflare.com/dns/zone-setups/full-setup/
#   - The bot is running on port 3000 (default — see PAYMENT_WEBHOOK_PORT).
#   - This script will open a browser-based login prompt on first run;
#     keep an LTE tab handy to approve the connection.

set -euo pipefail

HOSTNAME="${1:-}"
TUNNEL_NAME="${TUNNEL_NAME:-ariza}"
APP_DIR="${APP_DIR:-/var/www/ariza}"
LOCAL_PORT="${LOCAL_PORT:-3000}"

ENV_FILE="${APP_DIR}/.env"

if [[ -z "${HOSTNAME}" ]]; then
  cat <<'EOF' >&2
Usage:
  sudo bash deploy/setup-cloudflared.sh <hostname>

Example:
  sudo bash deploy/setup-cloudflared.sh ariza.mysite.uz

Environment overrides (optional):
  TUNNEL_NAME=ariza        # cloudflared tunnel name
  APP_DIR=/var/www/ariza   # bot install dir (holds .env)
  LOCAL_PORT=3000          # bot HTTP server port
EOF
  exit 1
fi

if [[ "${EUID}" -ne 0 ]]; then
  echo "Must run as root (use sudo)." >&2
  exit 1
fi

echo "==> [1/8] Install cloudflared if missing"
if ! command -v cloudflared >/dev/null 2>&1; then
  curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg \
    | tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null
  echo "deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared $(. /etc/os-release && echo $VERSION_CODENAME) main" \
    | tee /etc/apt/sources.list.d/cloudflared.list >/dev/null
  apt-get update
  apt-get install -y cloudflared
fi
cloudflared --version | head -n1

echo "==> [2/8] Cloudflare account login"
# `cloudflared tunnel login` opens a browser. On a headless server it
# prints a URL to open manually. The cert is written to
# /root/.cloudflared/cert.pem — we skip the call when it exists.
if [[ ! -f /root/.cloudflared/cert.pem ]]; then
  echo
  echo "    Cloudflare needs to open a URL in your browser."
  echo "    Copy the URL below, paste it into your LOCAL browser,"
  echo "    sign in, pick the zone (domain) for '${HOSTNAME}',"
  echo "    and approve. The script will continue once you're done."
  echo
  cloudflared tunnel login
else
  echo "    cert.pem already present — skipping login."
fi

echo "==> [3/8] Create tunnel '${TUNNEL_NAME}' (idempotent)"
if cloudflared tunnel list 2>/dev/null | awk 'NR>1 {print $2}' | grep -qx "${TUNNEL_NAME}"; then
  echo "    Tunnel '${TUNNEL_NAME}' already exists — reusing."
else
  cloudflared tunnel create "${TUNNEL_NAME}"
fi

# Cloudflared writes credentials to /root/.cloudflared/<UUID>.json
CREDS=$(find /root/.cloudflared -maxdepth 1 -name '*.json' -type f \
        -not -name 'cert.json' | head -n1)
if [[ -z "${CREDS}" ]]; then
  echo "Could not find tunnel credentials JSON under /root/.cloudflared" >&2
  exit 1
fi
TUNNEL_UUID="$(basename "${CREDS}" .json)"
echo "    Tunnel UUID: ${TUNNEL_UUID}"

echo "==> [4/8] Route DNS ${HOSTNAME} → tunnel ${TUNNEL_UUID}"
# Idempotent: cloudflared returns a friendly error if the route exists.
cloudflared tunnel route dns "${TUNNEL_NAME}" "${HOSTNAME}" || \
  echo "    (DNS route may already exist — that's fine.)"

echo "==> [5/8] Write /etc/cloudflared/config.yml"
mkdir -p /etc/cloudflared
cat > /etc/cloudflared/config.yml <<EOF
# Generated by deploy/setup-cloudflared.sh — safe to edit by hand,
# but a re-run of the script will overwrite it.

tunnel: ${TUNNEL_NAME}
credentials-file: ${CREDS}

# Single ingress rule: forward everything for ${HOSTNAME} to the bot's
# local HTTP server on port ${LOCAL_PORT}. The 404 catch-all is required
# by cloudflared as the last rule.
ingress:
  - hostname: ${HOSTNAME}
    service: http://localhost:${LOCAL_PORT}
  - service: http_status:404
EOF
chmod 644 /etc/cloudflared/config.yml

echo "==> [6/8] Install + enable systemd unit"
install -m 0644 "${APP_DIR}/deploy/cloudflared.service" \
        /etc/systemd/system/cloudflared.service
systemctl daemon-reload
systemctl enable cloudflared.service
systemctl restart cloudflared.service
sleep 2
systemctl --no-pager status cloudflared.service | head -n 12 || true

echo "==> [7/8] Update WEBAPP_URL in ${ENV_FILE}"
URL="https://${HOSTNAME}/webapp"
if [[ ! -f "${ENV_FILE}" ]]; then
  echo "WEBAPP_URL=${URL}" > "${ENV_FILE}"
else
  if grep -q '^WEBAPP_URL=' "${ENV_FILE}"; then
    sed -i "s|^WEBAPP_URL=.*|WEBAPP_URL=${URL}|" "${ENV_FILE}"
  else
    echo "WEBAPP_URL=${URL}" >> "${ENV_FILE}"
  fi
fi
echo "    WEBAPP_URL=${URL}"

echo "==> [8/8] Restart ariza-bot so it sees the new env var"
systemctl restart ariza-bot.service
sleep 1
systemctl --no-pager status ariza-bot.service | head -n 8 || true

echo
echo "==> Done."
echo
echo "    Public URL: ${URL}"
echo "    Health:     curl -I https://${HOSTNAME}/health"
echo "    API:        curl https://${HOSTNAME}/api/court-types | head -c 200"
echo "    Frontend:   open in browser → https://${HOSTNAME}/webapp"
echo
echo "    Logs:"
echo "      journalctl -u cloudflared -f"
echo "      journalctl -u ariza-bot   -f"
