/**
 * Scrape jadval2.sud.uz `jib/mhb` — the "Маъмурий ҳуқуқбузарликлар"
 * (administrative-offences) schedule module. This is the SECOND subtype
 * under the criminal-courts (`jib`) section; the first (`jib/jib`,
 * жиноят) is already in district-courts.generated.ts via scrape-courts.ts.
 *
 * These cases are heard by the same criminal courts, so the button ids
 * mirror the jinoyat ones — but the schedule API differs (api5.sud.uz),
 * so we keep them as their own `mhb` court type used ONLY by the
 * "📋 Ишимни текшириш" schedule flow.
 *
 * Run: npx tsx scripts/scrape-mhb.ts
 * Output: src/templates/mhb-courts.generated.ts (MHB_COURTS).
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { cyrillicToLatin } from '../src/i18n/transliterate';

const BASE = 'https://jadval2.sud.uz';
const BASE_PATH = 'jib/mhb';

const REGION_SLUG_MAP: Record<string, string> = {
  andijon: 'andijan',
  buxoro: 'bukhara',
  jizzax: 'jizzakh',
  qashqadaryo: 'kashkadarya',
  qoraqalpogiston: 'karakalpakstan',
  qoraqalpoq: 'karakalpakstan',
  qarqalpogiston: 'karakalpakstan',
  navoiy: 'navoi',
  navoi: 'navoi',
  namangan: 'namangan',
  samarqand: 'samarkand',
  sirdaryo: 'syrdarya',
  surxondaryo: 'surkhandarya',
  'toshkent-vil': 'tashkent_region',
  toshkentvil: 'tashkent_region',
  'toshkent-sh': 'tashkent_city',
  toshkentsh: 'tashkent_city',
  toshkent: 'tashkent_city',
  fargona: 'fergana',
  'fargʻona': 'fergana',
  xorazm: 'khorezm',
};

interface ScrapedCourt {
  code: string;
  regionCode: string;
  nameCY: string;
}

const sleep = (ms: number) => new Promise<void>((r) => setTimeout(r, ms));

async function fetchText(url: string, attempt = 1): Promise<string> {
  const res = await fetch(url, {
    headers: { 'User-Agent': 'Mozilla/5.0 (raport-bot mhb-scraper)' },
  });
  if (res.status >= 500 && res.status < 600 && attempt < 5) {
    await sleep(500 * attempt);
    return fetchText(url, attempt + 1);
  }
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
  return new TextDecoder('utf-8').decode(await res.arrayBuffer());
}

function parseRegionSlugs(html: string): string[] {
  const re = /<form\s+action\s*=\s*["']([^"']+?)-dis\.html["']/gi;
  const out: string[] = [];
  let m: RegExpExecArray | null;
  while ((m = re.exec(html)) !== null) out.push(m[1]!.trim());
  return [...new Set(out)];
}

function parseCourtButtons(html: string): { id: string; name: string }[] {
  const re =
    /<button\b[^>]*?\bid\s*=\s*["']([^"']+)["'][^>]*?\bvalue\s*=\s*["']([^"']+)["']/gi;
  const out: { id: string; name: string }[] = [];
  let m: RegExpExecArray | null;
  while ((m = re.exec(html)) !== null) out.push({ id: m[1]!.trim(), name: m[2]!.trim() });
  return out;
}

function esc(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

async function main() {
  console.log(`Scraping ${BASE}/${BASE_PATH} …`);
  const regionsHtml = await fetchText(`${BASE}/${BASE_PATH}/regions.html`);
  const slugs = parseRegionSlugs(regionsHtml);
  console.log(`regions: ${slugs.length} → ${slugs.join(', ')}`);

  const courts: ScrapedCourt[] = [];
  for (const slug of slugs) {
    const regionCode = REGION_SLUG_MAP[slug.toLowerCase()];
    if (!regionCode) {
      console.warn(`  ! unknown region slug: ${slug}`);
      continue;
    }
    await sleep(150);
    const html = await fetchText(`${BASE}/${BASE_PATH}/${slug}-dis.html`);
    const buttons = parseCourtButtons(html);
    for (const b of buttons) {
      courts.push({ code: `mhb-${regionCode}-${b.id}`, regionCode, nameCY: b.name });
    }
    console.log(`  ${slug} (${regionCode}): ${buttons.length} courts`);
  }

  const formatCourt = (c: ScrapedCourt): string =>
    [
      '  {',
      `    code: '${esc(c.code)}',`,
      `    regionCode: '${esc(c.regionCode)}',`,
      `    courtTypeCode: 'mhb',`,
      '    name: {',
      `      uz_cyrillic: '${esc(c.nameCY)}',`,
      `      uz_latin: '${esc(cyrillicToLatin(c.nameCY))}',`,
      `      ru: '${esc(c.nameCY)}',`,
      '    },',
      '  },',
    ].join('\n');

  const body = [
    '/* eslint-disable */',
    '// AUTO-GENERATED by scripts/scrape-mhb.ts — do not edit by hand.',
    `// Source: ${BASE}/${BASE_PATH}/regions.html (administrative-offences schedule).`,
    `// Count: ${courts.length} courts. Schedule API: https://api5.sud.uz/{id}/{DDMMYYYY}`,
    '',
    "import type { DistrictCourtDef } from './district-courts';",
    '',
    'export const MHB_COURTS: DistrictCourtDef[] = [',
    courts.map(formatCourt).join('\n'),
    '];',
    '',
  ].join('\n');

  const outPath = resolve(__dirname, '..', 'src', 'templates', 'mhb-courts.generated.ts');
  writeFileSync(outPath, body, 'utf-8');
  console.log(`\nTotal: ${courts.length} mhb courts → ${outPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
